/**
 * @file generated_filesystem.h
 * @brief Auto-generated filesystem format classes.
 * @warning Generated by scripts/gen_format_registry.py — do not edit.
 */
#ifndef DUMPFLOPPY_FORMATS_GENERATED_FILESYSTEM_H
#define DUMPFLOPPY_FORMATS_GENERATED_FILESYSTEM_H

#include "dumpfloppy/format.h"

#include "dumpfloppy/formats/archiveteam/at_adfs.h"
#include "dumpfloppy/formats/archiveteam/at_apple_dos.h"
#include "dumpfloppy/formats/archiveteam/at_atari_fms.h"
#include "dumpfloppy/formats/archiveteam/at_cbm_1581_fs.h"
#include "dumpfloppy/formats/archiveteam/at_cbmfs.h"
#include "dumpfloppy/formats/archiveteam/at_cpm.h"
#include "dumpfloppy/formats/archiveteam/at_fat.h"
#include "dumpfloppy/formats/archiveteam/at_fat8.h"
#include "dumpfloppy/formats/archiveteam/at_ffs.h"
#include "dumpfloppy/formats/archiveteam/at_hfs.h"
#include "dumpfloppy/formats/archiveteam/at_ofs.h"
#include "dumpfloppy/formats/archiveteam/at_prodos.h"
#include "dumpfloppy/formats/archiveteam/at_trdos_fs.h"

#include <vector>

namespace dumpfloppy
{

inline void append_generated_filesystem(std::vector<const file_format*>& out)
{
    static const formats::at_adfs generated_filesystem_0{};
    out.push_back(&generated_filesystem_0);
    static const formats::at_apple_dos generated_filesystem_1{};
    out.push_back(&generated_filesystem_1);
    static const formats::at_atari_fms generated_filesystem_2{};
    out.push_back(&generated_filesystem_2);
    static const formats::at_cbm_1581_fs generated_filesystem_3{};
    out.push_back(&generated_filesystem_3);
    static const formats::at_cbmfs generated_filesystem_4{};
    out.push_back(&generated_filesystem_4);
    static const formats::at_cpm generated_filesystem_5{};
    out.push_back(&generated_filesystem_5);
    static const formats::at_fat generated_filesystem_6{};
    out.push_back(&generated_filesystem_6);
    static const formats::at_fat8 generated_filesystem_7{};
    out.push_back(&generated_filesystem_7);
    static const formats::at_ffs generated_filesystem_8{};
    out.push_back(&generated_filesystem_8);
    static const formats::at_hfs generated_filesystem_9{};
    out.push_back(&generated_filesystem_9);
    static const formats::at_ofs generated_filesystem_10{};
    out.push_back(&generated_filesystem_10);
    static const formats::at_prodos generated_filesystem_11{};
    out.push_back(&generated_filesystem_11);
    static const formats::at_trdos_fs generated_filesystem_12{};
    out.push_back(&generated_filesystem_12);
}

} /* namespace dumpfloppy */

#endif /* DUMPFLOPPY_FORMATS_GENERATED_FILESYSTEM_H */
