/**
 * @file generated_container.h
 * @brief Auto-generated container format classes.
 * @warning Generated by scripts/gen_format_registry.py — do not edit.
 */
#ifndef DUMPFLOPPY_FORMATS_GENERATED_CONTAINER_H
#define DUMPFLOPPY_FORMATS_GENERATED_CONTAINER_H

#include "dumpfloppy/format.h"

#include "dumpfloppy/formats/archiveteam/at_86f.h"
#include "dumpfloppy/formats/archiveteam/at_a2r.h"
#include "dumpfloppy/formats/archiveteam/at_adf_amiga.h"
#include "dumpfloppy/formats/archiveteam/at_anex86_fdi.h"
#include "dumpfloppy/formats/archiveteam/at_apd.h"
#include "dumpfloppy/formats/archiveteam/at_apple_2img.h"
#include "dumpfloppy/formats/archiveteam/at_apridisk.h"
#include "dumpfloppy/formats/archiveteam/at_atr.h"
#include "dumpfloppy/formats/archiveteam/at_cfi.h"
#include "dumpfloppy/formats/archiveteam/at_copyqm.h"
#include "dumpfloppy/formats/archiveteam/at_cp2.h"
#include "dumpfloppy/formats/archiveteam/at_d64.h"
#include "dumpfloppy/formats/archiveteam/at_d88.h"
#include "dumpfloppy/formats/archiveteam/at_dart.h"
#include "dumpfloppy/formats/archiveteam/at_ddi.h"
#include "dumpfloppy/formats/archiveteam/at_dim_archiver.h"
#include "dumpfloppy/formats/archiveteam/at_disk_express.h"
#include "dumpfloppy/formats/archiveteam/at_disk_imploder.h"
#include "dumpfloppy/formats/archiveteam/at_dmf.h"
#include "dumpfloppy/formats/archiveteam/at_dmk.h"
#include "dumpfloppy/formats/archiveteam/at_dms_amiga.h"
#include "dumpfloppy/formats/archiveteam/at_dsk_apple2.h"
#include "dumpfloppy/formats/archiveteam/at_dsk_cpcemu.h"
#include "dumpfloppy/formats/archiveteam/at_dsk_oric.h"
#include "dumpfloppy/formats/archiveteam/at_dsq.h"
#include "dumpfloppy/formats/archiveteam/at_edd.h"
#include "dumpfloppy/formats/archiveteam/at_fdf.h"
#include "dumpfloppy/formats/archiveteam/at_fdi.h"
#include "dumpfloppy/formats/archiveteam/at_g64.h"
#include "dumpfloppy/formats/archiveteam/at_ima.h"
#include "dumpfloppy/formats/archiveteam/at_imd.h"
#include "dumpfloppy/formats/archiveteam/at_img_dosimg.h"
#include "dumpfloppy/formats/archiveteam/at_ipf.h"
#include "dumpfloppy/formats/archiveteam/at_jam_packer.h"
#include "dumpfloppy/formats/archiveteam/at_kryoflux.h"
#include "dumpfloppy/formats/archiveteam/at_ldbs.h"
#include "dumpfloppy/formats/archiveteam/at_loaddskf.h"
#include "dumpfloppy/formats/archiveteam/at_mirage_snx.h"
#include "dumpfloppy/formats/archiveteam/at_moof.h"
#include "dumpfloppy/formats/archiveteam/at_msa.h"
#include "dumpfloppy/formats/archiveteam/at_nufx.h"
#include "dumpfloppy/formats/archiveteam/at_pdi.h"
#include "dumpfloppy/formats/archiveteam/at_qrst.h"
#include "dumpfloppy/formats/archiveteam/at_raw_disk_image.h"
#include "dumpfloppy/formats/archiveteam/at_rim.h"
#include "dumpfloppy/formats/archiveteam/at_sabdu.h"
#include "dumpfloppy/formats/archiveteam/at_scp.h"
#include "dumpfloppy/formats/archiveteam/at_st.h"
#include "dumpfloppy/formats/archiveteam/at_stx.h"
#include "dumpfloppy/formats/archiveteam/at_sxd.h"
#include "dumpfloppy/formats/archiveteam/at_td0.h"
#include "dumpfloppy/formats/archiveteam/at_trd.h"
#include "dumpfloppy/formats/archiveteam/at_woz.h"
#include "dumpfloppy/formats/archiveteam/at_wrp.h"
#include "dumpfloppy/formats/archiveteam/at_xdf.h"
#include "dumpfloppy/formats/archiveteam/at_xpack.h"
#include "dumpfloppy/formats/archiveteam/at_zoom.h"

#include <vector>

namespace dumpfloppy
{

inline void append_generated_container(std::vector<const file_format*>& out)
{
    static const formats::at_86f generated_container_0{};
    out.push_back(&generated_container_0);
    static const formats::at_a2r generated_container_1{};
    out.push_back(&generated_container_1);
    static const formats::at_adf_amiga generated_container_2{};
    out.push_back(&generated_container_2);
    static const formats::at_anex86_fdi generated_container_3{};
    out.push_back(&generated_container_3);
    static const formats::at_apd generated_container_4{};
    out.push_back(&generated_container_4);
    static const formats::at_apple_2img generated_container_5{};
    out.push_back(&generated_container_5);
    static const formats::at_apridisk generated_container_6{};
    out.push_back(&generated_container_6);
    static const formats::at_atr generated_container_7{};
    out.push_back(&generated_container_7);
    static const formats::at_cfi generated_container_8{};
    out.push_back(&generated_container_8);
    static const formats::at_copyqm generated_container_9{};
    out.push_back(&generated_container_9);
    static const formats::at_cp2 generated_container_10{};
    out.push_back(&generated_container_10);
    static const formats::at_d64 generated_container_11{};
    out.push_back(&generated_container_11);
    static const formats::at_d88 generated_container_12{};
    out.push_back(&generated_container_12);
    static const formats::at_dart generated_container_13{};
    out.push_back(&generated_container_13);
    static const formats::at_ddi generated_container_14{};
    out.push_back(&generated_container_14);
    static const formats::at_dim_archiver generated_container_15{};
    out.push_back(&generated_container_15);
    static const formats::at_disk_express generated_container_16{};
    out.push_back(&generated_container_16);
    static const formats::at_disk_imploder generated_container_17{};
    out.push_back(&generated_container_17);
    static const formats::at_dmf generated_container_18{};
    out.push_back(&generated_container_18);
    static const formats::at_dmk generated_container_19{};
    out.push_back(&generated_container_19);
    static const formats::at_dms_amiga generated_container_20{};
    out.push_back(&generated_container_20);
    static const formats::at_dsk_apple2 generated_container_21{};
    out.push_back(&generated_container_21);
    static const formats::at_dsk_cpcemu generated_container_22{};
    out.push_back(&generated_container_22);
    static const formats::at_dsk_oric generated_container_23{};
    out.push_back(&generated_container_23);
    static const formats::at_dsq generated_container_24{};
    out.push_back(&generated_container_24);
    static const formats::at_edd generated_container_25{};
    out.push_back(&generated_container_25);
    static const formats::at_fdf generated_container_26{};
    out.push_back(&generated_container_26);
    static const formats::at_fdi generated_container_27{};
    out.push_back(&generated_container_27);
    static const formats::at_g64 generated_container_28{};
    out.push_back(&generated_container_28);
    static const formats::at_ima generated_container_29{};
    out.push_back(&generated_container_29);
    static const formats::at_imd generated_container_30{};
    out.push_back(&generated_container_30);
    static const formats::at_img_dosimg generated_container_31{};
    out.push_back(&generated_container_31);
    static const formats::at_ipf generated_container_32{};
    out.push_back(&generated_container_32);
    static const formats::at_jam_packer generated_container_33{};
    out.push_back(&generated_container_33);
    static const formats::at_kryoflux generated_container_34{};
    out.push_back(&generated_container_34);
    static const formats::at_ldbs generated_container_35{};
    out.push_back(&generated_container_35);
    static const formats::at_loaddskf generated_container_36{};
    out.push_back(&generated_container_36);
    static const formats::at_mirage_snx generated_container_37{};
    out.push_back(&generated_container_37);
    static const formats::at_moof generated_container_38{};
    out.push_back(&generated_container_38);
    static const formats::at_msa generated_container_39{};
    out.push_back(&generated_container_39);
    static const formats::at_nufx generated_container_40{};
    out.push_back(&generated_container_40);
    static const formats::at_pdi generated_container_41{};
    out.push_back(&generated_container_41);
    static const formats::at_qrst generated_container_42{};
    out.push_back(&generated_container_42);
    static const formats::at_raw_disk_image generated_container_43{};
    out.push_back(&generated_container_43);
    static const formats::at_rim generated_container_44{};
    out.push_back(&generated_container_44);
    static const formats::at_sabdu generated_container_45{};
    out.push_back(&generated_container_45);
    static const formats::at_scp generated_container_46{};
    out.push_back(&generated_container_46);
    static const formats::at_st generated_container_47{};
    out.push_back(&generated_container_47);
    static const formats::at_stx generated_container_48{};
    out.push_back(&generated_container_48);
    static const formats::at_sxd generated_container_49{};
    out.push_back(&generated_container_49);
    static const formats::at_td0 generated_container_50{};
    out.push_back(&generated_container_50);
    static const formats::at_trd generated_container_51{};
    out.push_back(&generated_container_51);
    static const formats::at_woz generated_container_52{};
    out.push_back(&generated_container_52);
    static const formats::at_wrp generated_container_53{};
    out.push_back(&generated_container_53);
    static const formats::at_xdf generated_container_54{};
    out.push_back(&generated_container_54);
    static const formats::at_xpack generated_container_55{};
    out.push_back(&generated_container_55);
    static const formats::at_zoom generated_container_56{};
    out.push_back(&generated_container_56);
}

} /* namespace dumpfloppy */

#endif /* DUMPFLOPPY_FORMATS_GENERATED_CONTAINER_H */
