/**
 * @file generated_formats.h
 * @brief Auto-generated includes + table of wiki format classes.
 * @warning Generated by scripts/gen_format_registry.py — do not edit.
 */
#ifndef DUMPFLOPPY_FORMATS_GENERATED_FORMATS_H
#define DUMPFLOPPY_FORMATS_GENERATED_FORMATS_H

#include "dumpfloppy/format.h"

#include "dumpfloppy/formats/archiveteam/at_86f.h"
#include "dumpfloppy/formats/archiveteam/at_a2r.h"
#include "dumpfloppy/formats/archiveteam/at_adf_amiga.h"
#include "dumpfloppy/formats/archiveteam/at_adfs.h"
#include "dumpfloppy/formats/archiveteam/at_anex86_fdi.h"
#include "dumpfloppy/formats/archiveteam/at_apd.h"
#include "dumpfloppy/formats/archiveteam/at_apple_2img.h"
#include "dumpfloppy/formats/archiveteam/at_apple_dos.h"
#include "dumpfloppy/formats/archiveteam/at_apridisk.h"
#include "dumpfloppy/formats/archiveteam/at_atari_fms.h"
#include "dumpfloppy/formats/archiveteam/at_atr.h"
#include "dumpfloppy/formats/archiveteam/at_cbm_1581_fs.h"
#include "dumpfloppy/formats/archiveteam/at_cbmfs.h"
#include "dumpfloppy/formats/archiveteam/at_cfi.h"
#include "dumpfloppy/formats/archiveteam/at_copyqm.h"
#include "dumpfloppy/formats/archiveteam/at_cp2.h"
#include "dumpfloppy/formats/archiveteam/at_cpm.h"
#include "dumpfloppy/formats/archiveteam/at_d64.h"
#include "dumpfloppy/formats/archiveteam/at_d88.h"
#include "dumpfloppy/formats/archiveteam/at_dart.h"
#include "dumpfloppy/formats/archiveteam/at_ddi.h"
#include "dumpfloppy/formats/archiveteam/at_dim_archiver.h"
#include "dumpfloppy/formats/archiveteam/at_disk_express.h"
#include "dumpfloppy/formats/archiveteam/at_disk_imploder.h"
#include "dumpfloppy/formats/archiveteam/at_dmf.h"
#include "dumpfloppy/formats/archiveteam/at_dmk.h"
#include "dumpfloppy/formats/archiveteam/at_dms_amiga.h"
#include "dumpfloppy/formats/archiveteam/at_dsk_apple2.h"
#include "dumpfloppy/formats/archiveteam/at_dsk_cpcemu.h"
#include "dumpfloppy/formats/archiveteam/at_dsk_oric.h"
#include "dumpfloppy/formats/archiveteam/at_dsq.h"
#include "dumpfloppy/formats/archiveteam/at_edd.h"
#include "dumpfloppy/formats/archiveteam/at_fat.h"
#include "dumpfloppy/formats/archiveteam/at_fat8.h"
#include "dumpfloppy/formats/archiveteam/at_fdf.h"
#include "dumpfloppy/formats/archiveteam/at_fdi.h"
#include "dumpfloppy/formats/archiveteam/at_ffs.h"
#include "dumpfloppy/formats/archiveteam/at_g64.h"
#include "dumpfloppy/formats/archiveteam/at_hfs.h"
#include "dumpfloppy/formats/archiveteam/at_ima.h"
#include "dumpfloppy/formats/archiveteam/at_imd.h"
#include "dumpfloppy/formats/archiveteam/at_img_dosimg.h"
#include "dumpfloppy/formats/archiveteam/at_ipf.h"
#include "dumpfloppy/formats/archiveteam/at_jam_packer.h"
#include "dumpfloppy/formats/archiveteam/at_kryoflux.h"
#include "dumpfloppy/formats/archiveteam/at_ldbs.h"
#include "dumpfloppy/formats/archiveteam/at_loaddskf.h"
#include "dumpfloppy/formats/archiveteam/at_mirage_snx.h"
#include "dumpfloppy/formats/archiveteam/at_moof.h"
#include "dumpfloppy/formats/archiveteam/at_msa.h"
#include "dumpfloppy/formats/archiveteam/at_nufx.h"
#include "dumpfloppy/formats/archiveteam/at_ofs.h"
#include "dumpfloppy/formats/archiveteam/at_pdi.h"
#include "dumpfloppy/formats/archiveteam/at_prodos.h"
#include "dumpfloppy/formats/archiveteam/at_qrst.h"
#include "dumpfloppy/formats/archiveteam/at_raw_disk_image.h"
#include "dumpfloppy/formats/archiveteam/at_rim.h"
#include "dumpfloppy/formats/archiveteam/at_sabdu.h"
#include "dumpfloppy/formats/archiveteam/at_scp.h"
#include "dumpfloppy/formats/archiveteam/at_st.h"
#include "dumpfloppy/formats/archiveteam/at_stx.h"
#include "dumpfloppy/formats/archiveteam/at_sxd.h"
#include "dumpfloppy/formats/archiveteam/at_td0.h"
#include "dumpfloppy/formats/archiveteam/at_trd.h"
#include "dumpfloppy/formats/archiveteam/at_trdos_fs.h"
#include "dumpfloppy/formats/archiveteam/at_woz.h"
#include "dumpfloppy/formats/archiveteam/at_wrp.h"
#include "dumpfloppy/formats/archiveteam/at_xdf.h"
#include "dumpfloppy/formats/archiveteam/at_xpack.h"
#include "dumpfloppy/formats/archiveteam/at_zoom.h"
#include "dumpfloppy/formats/shikadi/sk_3o_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_4md.h"
#include "dumpfloppy/formats/shikadi/sk_4x4_off_road_racing_full_screen_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_4x4_off_road_racing_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_4x4_off_road_racing_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_instrument.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_instrument_bank.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_midi.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_sound_effect.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_timbre_bank.h"
#include "dumpfloppy/formats/shikadi/sk_agos_vga.h"
#include "dumpfloppy/formats/shikadi/sk_aiff.h"
#include "dumpfloppy/formats/shikadi/sk_all_dogs_archive.h"
#include "dumpfloppy/formats/shikadi/sk_all_dogs_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_amf.h"
#include "dumpfloppy/formats/shikadi/sk_ani_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_apogee_sound_system_timbre.h"
#include "dumpfloppy/formats/shikadi/sk_art_build.h"
#include "dumpfloppy/formats/shikadi/sk_artcraft_resource_file.h"
#include "dumpfloppy/formats/shikadi/sk_audiot.h"
#include "dumpfloppy/formats/shikadi/sk_b800_text.h"
#include "dumpfloppy/formats/shikadi/sk_battle_isle_history_line_library.h"
#include "dumpfloppy/formats/shikadi/sk_battle_isle_history_line_map.h"
#include "dumpfloppy/formats/shikadi/sk_bgi_stroked_font.h"
#include "dumpfloppy/formats/shikadi/sk_bin_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_bin_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_blk_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_bmc.h"
#include "dumpfloppy/formats/shikadi/sk_bnk_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_bodyworks_voyager_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_borland_graphics_interface.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_dialog.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_map.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_image.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_map.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_car_carnivores.h"
#include "dumpfloppy/formats/shikadi/sk_car_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_carmack_compression.h"
#include "dumpfloppy/formats/shikadi/sk_castle_adventure_data.h"
#include "dumpfloppy/formats/shikadi/sk_castles_ii_siege_and_conquest_cluster.h"
#include "dumpfloppy/formats/shikadi/sk_castles_ii_siege_and_conquest_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_cat_mps_labs.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_highscore.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_map.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_cc.h"
#include "dumpfloppy/formats/shikadi/sk_cc1.h"
#include "dumpfloppy/formats/shikadi/sk_cdfm.h"
#include "dumpfloppy/formats/shikadi/sk_cel_image.h"
#include "dumpfloppy/formats/shikadi/sk_centurion_font.h"
#include "dumpfloppy/formats/shikadi/sk_cfg_f1_manager_professional.h"
#include "dumpfloppy/formats/shikadi/sk_cfg_jill_of_the_jungle.h"
#include "dumpfloppy/formats/shikadi/sk_cga_palette.h"
#include "dumpfloppy/formats/shikadi/sk_chasm_inf.h"
#include "dumpfloppy/formats/shikadi/sk_chr_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_cmf.h"
#include "dumpfloppy/formats/shikadi/sk_cmp.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_mission.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_red_alert_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_red_alert_vortex_lookup_table.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_commander_keen_1_3_level.h"
#include "dumpfloppy/formats/shikadi/sk_commander_keen_1_3_score.h"
#include "dumpfloppy/formats/shikadi/sk_commander_keen_ega_header.h"
#include "dumpfloppy/formats/shikadi/sk_con.h"
#include "dumpfloppy/formats/shikadi/sk_cosmo_level.h"
#include "dumpfloppy/formats/shikadi/sk_cosmo_tileinfo.h"
#include "dumpfloppy/formats/shikadi/sk_cosmo_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_cover_girl_strip_poker_font.h"
#include "dumpfloppy/formats/shikadi/sk_cover_girl_strip_poker_text.h"
#include "dumpfloppy/formats/shikadi/sk_crunched_screen_image.h"
#include "dumpfloppy/formats/shikadi/sk_crystal_caves_map.h"
#include "dumpfloppy/formats/shikadi/sk_crystal_caves_sound.h"
#include "dumpfloppy/formats/shikadi/sk_cur.h"
#include "dumpfloppy/formats/shikadi/sk_dangerous_dave_level.h"
#include "dumpfloppy/formats/shikadi/sk_dangerous_dave_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_dark_ages_map.h"
#include "dumpfloppy/formats/shikadi/sk_dat_bullfrog.h"
#include "dumpfloppy/formats/shikadi/sk_dat_california_games_ii.h"
#include "dumpfloppy/formats/shikadi/sk_dat_centurion_defender_of_rome.h"
#include "dumpfloppy/formats/shikadi/sk_dat_dr_riptide.h"
#include "dumpfloppy/formats/shikadi/sk_dat_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_dat_god_of_thunder.h"
#include "dumpfloppy/formats/shikadi/sk_dat_highway_hunter.h"
#include "dumpfloppy/formats/shikadi/sk_dat_hocus_pocus.h"
#include "dumpfloppy/formats/shikadi/sk_dat_hugo.h"
#include "dumpfloppy/formats/shikadi/sk_dat_monster_bash.h"
#include "dumpfloppy/formats/shikadi/sk_dat_mystic_towers.h"
#include "dumpfloppy/formats/shikadi/sk_dat_papyrus.h"
#include "dumpfloppy/formats/shikadi/sk_dat_sango_fighter.h"
#include "dumpfloppy/formats/shikadi/sk_dat_the_lost_vikings.h"
#include "dumpfloppy/formats/shikadi/sk_dat_wacky_wheels.h"
#include "dumpfloppy/formats/shikadi/sk_dat_zool.h"
#include "dumpfloppy/formats/shikadi/sk_dave_2_huffman_compression.h"
#include "dumpfloppy/formats/shikadi/sk_dave_2_intro.h"
#include "dumpfloppy/formats/shikadi/sk_dave_2_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_dave_score.h"
#include "dumpfloppy/formats/shikadi/sk_ddici_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_bpa.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_bpk.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_cmf.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_haf.h"
#include "dumpfloppy/formats/shikadi/sk_del.h"
#include "dumpfloppy/formats/shikadi/sk_demo_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_dlt.h"
#include "dumpfloppy/formats/shikadi/sk_dma.h"
#include "dumpfloppy/formats/shikadi/sk_dmp.h"
#include "dumpfloppy/formats/shikadi/sk_doofus_game_data.h"
#include "dumpfloppy/formats/shikadi/sk_dro.h"
#include "dumpfloppy/formats/shikadi/sk_dsik_config.h"
#include "dumpfloppy/formats/shikadi/sk_dsik_module.h"
#include "dumpfloppy/formats/shikadi/sk_dta_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_duke_1_demo.h"
#include "dumpfloppy/formats/shikadi/sk_duke_1_level.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_3d_palette.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_actor_info.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_animation.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_czone.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_demo.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_full_screen_images.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_map.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_misc_files.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_palette.h"
#include "dumpfloppy/formats/shikadi/sk_dune_2000_font.h"
#include "dumpfloppy/formats/shikadi/sk_dungeons_of_the_unforgiven_character_creation_text.h"
#include "dumpfloppy/formats/shikadi/sk_dungeons_of_the_unforgiven_player_character.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v1.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v2_v3.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v4_v5.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v6.h"
#include "dumpfloppy/formats/shikadi/sk_ega_palette.h"
#include "dumpfloppy/formats/shikadi/sk_egagraph.h"
#include "dumpfloppy/formats/shikadi/sk_epf.h"
#include "dumpfloppy/formats/shikadi/sk_esi.h"
#include "dumpfloppy/formats/shikadi/sk_exe.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_archive.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_font.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_rle.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_palette.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_vcn.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_vmp.h"
#include "dumpfloppy/formats/shikadi/sk_family_feud_question.h"
#include "dumpfloppy/formats/shikadi/sk_family_feud_question_flag.h"
#include "dumpfloppy/formats/shikadi/sk_family_feud_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_flic.h"
#include "dumpfloppy/formats/shikadi/sk_gamedat_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_gamemaps.h"
#include "dumpfloppy/formats/shikadi/sk_gem_font.h"
#include "dumpfloppy/formats/shikadi/sk_glb_galactix.h"
#include "dumpfloppy/formats/shikadi/sk_glb_raptor.h"
#include "dumpfloppy/formats/shikadi/sk_global_timbre_library.h"
#include "dumpfloppy/formats/shikadi/sk_gmf_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_god_of_thunder_level.h"
#include "dumpfloppy/formats/shikadi/sk_god_of_thunder_music.h"
#include "dumpfloppy/formats/shikadi/sk_god_of_thunder_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_graphics_interchange.h"
#include "dumpfloppy/formats/shikadi/sk_grp.h"
#include "dumpfloppy/formats/shikadi/sk_gx2.h"
#include "dumpfloppy/formats/shikadi/sk_gx_library.h"
#include "dumpfloppy/formats/shikadi/sk_halloween_harry_dialogue.h"
#include "dumpfloppy/formats/shikadi/sk_heretic_executable.h"
#include "dumpfloppy/formats/shikadi/sk_heroquest_exe_file.h"
#include "dumpfloppy/formats/shikadi/sk_heroquest_quest.h"
#include "dumpfloppy/formats/shikadi/sk_heroquest_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_hi_octane_texture_atlas.h"
#include "dumpfloppy/formats/shikadi/sk_hi_zzt.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_image.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_map.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_palette.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_sfx.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_text.h"
#include "dumpfloppy/formats/shikadi/sk_hog.h"
#include "dumpfloppy/formats/shikadi/sk_homebrew_file_folder.h"
#include "dumpfloppy/formats/shikadi/sk_hs_major_stryker.h"
#include "dumpfloppy/formats/shikadi/sk_hsb_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_huffman_compression.h"
#include "dumpfloppy/formats/shikadi/sk_hugo_map.h"
#include "dumpfloppy/formats/shikadi/sk_human_machine_interfaces_midi.h"
#include "dumpfloppy/formats/shikadi/sk_ibk.h"
#include "dumpfloppy/formats/shikadi/sk_ico_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_id_software_rlew_compression.h"
#include "dumpfloppy/formats/shikadi/sk_imf.h"
#include "dumpfloppy/formats/shikadi/sk_img_meen.h"
#include "dumpfloppy/formats/shikadi/sk_imm_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_ims.h"
#include "dumpfloppy/formats/shikadi/sk_indy_500_library.h"
#include "dumpfloppy/formats/shikadi/sk_ins_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_int_33_graphics_pointer_shape.h"
#include "dumpfloppy/formats/shikadi/sk_inverse_frequency_sound.h"
#include "dumpfloppy/formats/shikadi/sk_isle_of_the_dead_font.h"
#include "dumpfloppy/formats/shikadi/sk_jam.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_2_music.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_bonus.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_bonusmap.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_cutscene.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_demo.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_font.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_map.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_menu.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_panel.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_planet.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_score.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_sound.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_tile.h"
#include "dumpfloppy/formats/shikadi/sk_jill_of_the_jungle_map.h"
#include "dumpfloppy/formats/shikadi/sk_joesnd.h"
#include "dumpfloppy/formats/shikadi/sk_karl_morton_music.h"
#include "dumpfloppy/formats/shikadi/sk_keen_1_3_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_keen_1_3_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_map.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_music.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_kings_of_the_beach_font.h"
#include "dumpfloppy/formats/shikadi/sk_kings_of_the_beach_pak.h"
#include "dumpfloppy/formats/shikadi/sk_klm.h"
#include "dumpfloppy/formats/shikadi/sk_kmd_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_knowledge_dynamics_lzw_compressor.h"
#include "dumpfloppy/formats/shikadi/sk_kort_bmp.h"
#include "dumpfloppy/formats/shikadi/sk_kort_font.h"
#include "dumpfloppy/formats/shikadi/sk_kort_image.h"
#include "dumpfloppy/formats/shikadi/sk_kort_sound_archive.h"
#include "dumpfloppy/formats/shikadi/sk_kris_music_system.h"
#include "dumpfloppy/formats/shikadi/sk_kris_music_system_voice.h"
#include "dumpfloppy/formats/shikadi/sk_kvx_build.h"
#include "dumpfloppy/formats/shikadi/sk_lang_txt_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_lbm.h"
#include "dumpfloppy/formats/shikadi/sk_lbr.h"
#include "dumpfloppy/formats/shikadi/sk_lbx.h"
#include "dumpfloppy/formats/shikadi/sk_legend_of_seven_paladins_3d_archive.h"
#include "dumpfloppy/formats/shikadi/sk_lib_electronic_arts.h"
#include "dumpfloppy/formats/shikadi/sk_lib_mythos_software.h"
#include "dumpfloppy/formats/shikadi/sk_linear_executable_lx_le.h"
#include "dumpfloppy/formats/shikadi/sk_lion_king_level.h"
#include "dumpfloppy/formats/shikadi/sk_lmh_lmo_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_lpcm.h"
#include "dumpfloppy/formats/shikadi/sk_lzss_compression.h"
#include "dumpfloppy/formats/shikadi/sk_lzw_compression.h"
#include "dumpfloppy/formats/shikadi/sk_m.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_level.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_text.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_map_build.h"
#include "dumpfloppy/formats/shikadi/sk_map_shadowcaster.h"
#include "dumpfloppy/formats/shikadi/sk_mat.h"
#include "dumpfloppy/formats/shikadi/sk_mch.h"
#include "dumpfloppy/formats/shikadi/sk_mdi.h"
#include "dumpfloppy/formats/shikadi/sk_megatech_vol.h"
#include "dumpfloppy/formats/shikadi/sk_messages_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_basic_mml.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_bitmap_font.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_exepack.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_vector_font.h"
#include "dumpfloppy/formats/shikadi/sk_mid.h"
#include "dumpfloppy/formats/shikadi/sk_miscellaneous_wacky_wheels_file.h"
#include "dumpfloppy/formats/shikadi/sk_mix_westwood.h"
#include "dumpfloppy/formats/shikadi/sk_mod.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_level.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_moraff_help_file.h"
#include "dumpfloppy/formats/shikadi/sk_moraff_monster_map.h"
#include "dumpfloppy/formats/shikadi/sk_mus.h"
#include "dumpfloppy/formats/shikadi/sk_mystic_towers_pc_speaker_sound.h"
#include "dumpfloppy/formats/shikadi/sk_mystic_towers_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_nnv.h"
#include "dumpfloppy/formats/shikadi/sk_nomad_3d_model.h"
#include "dumpfloppy/formats/shikadi/sk_nomad_sound.h"
#include "dumpfloppy/formats/shikadi/sk_nomad_text.h"
#include "dumpfloppy/formats/shikadi/sk_nova.h"
#include "dumpfloppy/formats/shikadi/sk_op2_bank.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_dialogue.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_high_scores.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_joystick_calibration.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_tombstones.h"
#include "dumpfloppy/formats/shikadi/sk_paganitzu_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_paganitzu_level.h"
#include "dumpfloppy/formats/shikadi/sk_pak_the_learning_company.h"
#include "dumpfloppy/formats/shikadi/sk_pak_westwood.h"
#include "dumpfloppy/formats/shikadi/sk_papyrus_palette.h"
#include "dumpfloppy/formats/shikadi/sk_pcx.h"
#include "dumpfloppy/formats/shikadi/sk_pcx_library.h"
#include "dumpfloppy/formats/shikadi/sk_pharaohs_tomb_and_arctic_adventure_fullscreen_image.h"
#include "dumpfloppy/formats/shikadi/sk_pic.h"
#include "dumpfloppy/formats/shikadi/sk_pic_sexonix.h"
#include "dumpfloppy/formats/shikadi/sk_pod.h"
#include "dumpfloppy/formats/shikadi/sk_pr2.h"
#include "dumpfloppy/formats/shikadi/sk_pref_dat_witchaven.h"
#include "dumpfloppy/formats/shikadi/sk_prehistorik_level.h"
#include "dumpfloppy/formats/shikadi/sk_prographx_toolbox_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_prot_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_protracker_studio_module.h"
#include "dumpfloppy/formats/shikadi/sk_raptor_animated_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_raptor_pic.h"
#include "dumpfloppy/formats/shikadi/sk_raptor_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_raw_adlib.h"
#include "dumpfloppy/formats/shikadi/sk_raw_cga_data.h"
#include "dumpfloppy/formats/shikadi/sk_raw_ega_data.h"
#include "dumpfloppy/formats/shikadi/sk_raw_vga_image.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_level.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_masked_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_res_boppin.h"
#include "dumpfloppy/formats/shikadi/sk_res_stellar_7.h"
#include "dumpfloppy/formats/shikadi/sk_rescue_rover_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_rff.h"
#include "dumpfloppy/formats/shikadi/sk_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_rob_northern_compression.h"
#include "dumpfloppy/formats/shikadi/sk_rol.h"
#include "dumpfloppy/formats/shikadi/sk_rol_image_archive.h"
#include "dumpfloppy/formats/shikadi/sk_rsc_battlestar.h"
#include "dumpfloppy/formats/shikadi/sk_rsc_f1_manager_professional.h"
#include "dumpfloppy/formats/shikadi/sk_rtl.h"
#include "dumpfloppy/formats/shikadi/sk_rts.h"
#include "dumpfloppy/formats/shikadi/sk_s3m.h"
#include "dumpfloppy/formats/shikadi/sk_sango_fighter_rlc_compression.h"
#include "dumpfloppy/formats/shikadi/sk_sav_hocus_pocus.h"
#include "dumpfloppy/formats/shikadi/sk_sbi.h"
#include "dumpfloppy/formats/shikadi/sk_secret_agent_level.h"
#include "dumpfloppy/formats/shikadi/sk_selectware_archive.h"
#include "dumpfloppy/formats/shikadi/sk_setup_dat_witchaven.h"
#include "dumpfloppy/formats/shikadi/sk_sha.h"
#include "dumpfloppy/formats/shikadi/sk_shadow_warrior_1993_beta_background_image.h"
#include "dumpfloppy/formats/shikadi/sk_shadow_warrior_1993_beta_image.h"
#include "dumpfloppy/formats/shikadi/sk_shaws_nightmare_archive.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_compression.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_image.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_level.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_slb.h"
#include "dumpfloppy/formats/shikadi/sk_smacker_video.h"
#include "dumpfloppy/formats/shikadi/sk_softdisk_library.h"
#include "dumpfloppy/formats/shikadi/sk_softmax_resource_file.h"
#include "dumpfloppy/formats/shikadi/sk_solar_winds_sprites.h"
#include "dumpfloppy/formats/shikadi/sk_sop.h"
#include "dumpfloppy/formats/shikadi/sk_space_crusade_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_space_quest_v_font.h"
#include "dumpfloppy/formats/shikadi/sk_ssp.h"
#include "dumpfloppy/formats/shikadi/sk_stargunner_sprites.h"
#include "dumpfloppy/formats/shikadi/sk_stp.h"
#include "dumpfloppy/formats/shikadi/sk_super_street_fighter_ii_turbo_movie.h"
#include "dumpfloppy/formats/shikadi/sk_super_street_fighter_ii_turbo_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_fortune.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_info.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_map.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_message.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_monster.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_names.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_people.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_puzzle.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_vault.h"
#include "dumpfloppy/formats/shikadi/sk_tbsa_music.h"
#include "dumpfloppy/formats/shikadi/sk_the_blues_brothers_huffman_compression.h"
#include "dumpfloppy/formats/shikadi/sk_the_blues_brothers_map.h"
#include "dumpfloppy/formats/shikadi/sk_the_blues_brothers_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_the_incredible_machine_2_3_anm_file.h"
#include "dumpfloppy/formats/shikadi/sk_the_incredible_machine_image.h"
#include "dumpfloppy/formats/shikadi/sk_the_incredible_machine_level.h"
#include "dumpfloppy/formats/shikadi/sk_tim_resource.h"
#include "dumpfloppy/formats/shikadi/sk_titus_interactive_sqz_compression.h"
#include "dumpfloppy/formats/shikadi/sk_top_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_transylvania_font.h"
#include "dumpfloppy/formats/shikadi/sk_treasure_mountain_panning_image.h"
#include "dumpfloppy/formats/shikadi/sk_treasure_mountain_save_file.h"
#include "dumpfloppy/formats/shikadi/sk_trugg_level.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_full_screen_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_map.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_tile_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_town_map.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_ii_dungeon.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_ii_map.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_ii_talk.h"
#include "dumpfloppy/formats/shikadi/sk_vga_palette.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_level.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_raw_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_save.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_screen.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_viacom_new_media_graphics_file.h"
#include "dumpfloppy/formats/shikadi/sk_visage.h"
#include "dumpfloppy/formats/shikadi/sk_visage_animation.h"
#include "dumpfloppy/formats/shikadi/sk_voc.h"
#include "dumpfloppy/formats/shikadi/sk_wacky_wheels_configuration.h"
#include "dumpfloppy/formats/shikadi/sk_wacky_wheels_high_score_files.h"
#include "dumpfloppy/formats/shikadi/sk_wacky_wheels_track.h"
#include "dumpfloppy/formats/shikadi/sk_wad.h"
#include "dumpfloppy/formats/shikadi/sk_wasteland_pic.h"
#include "dumpfloppy/formats/shikadi/sk_wav.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_aud.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_bitfont.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_cmp.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_cps.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_fading_table.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v1.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v2.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v3.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v4.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_lcw.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_lzw_12.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_lzw_14.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_rle.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_rle_zero.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_dune_ii.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_lands_of_lore.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_td.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_ts.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_unicode_bitfont.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_wsa.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_xor_delta.h"
#include "dumpfloppy/formats/shikadi/sk_wing_commander_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_demo.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_highscore.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_level.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_xmi.h"
#include "dumpfloppy/formats/shikadi/sk_zlib_compression.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_compression.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_high_scores.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_level.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_zzt.h"

#include <vector>

namespace dumpfloppy
{

inline void append_generated_formats(std::vector<const file_format*>& out)
{
    static const formats::at_86f generated_0{};
    out.push_back(&generated_0);
    static const formats::at_a2r generated_1{};
    out.push_back(&generated_1);
    static const formats::at_adf_amiga generated_2{};
    out.push_back(&generated_2);
    static const formats::at_adfs generated_3{};
    out.push_back(&generated_3);
    static const formats::at_anex86_fdi generated_4{};
    out.push_back(&generated_4);
    static const formats::at_apd generated_5{};
    out.push_back(&generated_5);
    static const formats::at_apple_2img generated_6{};
    out.push_back(&generated_6);
    static const formats::at_apple_dos generated_7{};
    out.push_back(&generated_7);
    static const formats::at_apridisk generated_8{};
    out.push_back(&generated_8);
    static const formats::at_atari_fms generated_9{};
    out.push_back(&generated_9);
    static const formats::at_atr generated_10{};
    out.push_back(&generated_10);
    static const formats::at_cbm_1581_fs generated_11{};
    out.push_back(&generated_11);
    static const formats::at_cbmfs generated_12{};
    out.push_back(&generated_12);
    static const formats::at_cfi generated_13{};
    out.push_back(&generated_13);
    static const formats::at_copyqm generated_14{};
    out.push_back(&generated_14);
    static const formats::at_cp2 generated_15{};
    out.push_back(&generated_15);
    static const formats::at_cpm generated_16{};
    out.push_back(&generated_16);
    static const formats::at_d64 generated_17{};
    out.push_back(&generated_17);
    static const formats::at_d88 generated_18{};
    out.push_back(&generated_18);
    static const formats::at_dart generated_19{};
    out.push_back(&generated_19);
    static const formats::at_ddi generated_20{};
    out.push_back(&generated_20);
    static const formats::at_dim_archiver generated_21{};
    out.push_back(&generated_21);
    static const formats::at_disk_express generated_22{};
    out.push_back(&generated_22);
    static const formats::at_disk_imploder generated_23{};
    out.push_back(&generated_23);
    static const formats::at_dmf generated_24{};
    out.push_back(&generated_24);
    static const formats::at_dmk generated_25{};
    out.push_back(&generated_25);
    static const formats::at_dms_amiga generated_26{};
    out.push_back(&generated_26);
    static const formats::at_dsk_apple2 generated_27{};
    out.push_back(&generated_27);
    static const formats::at_dsk_cpcemu generated_28{};
    out.push_back(&generated_28);
    static const formats::at_dsk_oric generated_29{};
    out.push_back(&generated_29);
    static const formats::at_dsq generated_30{};
    out.push_back(&generated_30);
    static const formats::at_edd generated_31{};
    out.push_back(&generated_31);
    static const formats::at_fat generated_32{};
    out.push_back(&generated_32);
    static const formats::at_fat8 generated_33{};
    out.push_back(&generated_33);
    static const formats::at_fdf generated_34{};
    out.push_back(&generated_34);
    static const formats::at_fdi generated_35{};
    out.push_back(&generated_35);
    static const formats::at_ffs generated_36{};
    out.push_back(&generated_36);
    static const formats::at_g64 generated_37{};
    out.push_back(&generated_37);
    static const formats::at_hfs generated_38{};
    out.push_back(&generated_38);
    static const formats::at_ima generated_39{};
    out.push_back(&generated_39);
    static const formats::at_imd generated_40{};
    out.push_back(&generated_40);
    static const formats::at_img_dosimg generated_41{};
    out.push_back(&generated_41);
    static const formats::at_ipf generated_42{};
    out.push_back(&generated_42);
    static const formats::at_jam_packer generated_43{};
    out.push_back(&generated_43);
    static const formats::at_kryoflux generated_44{};
    out.push_back(&generated_44);
    static const formats::at_ldbs generated_45{};
    out.push_back(&generated_45);
    static const formats::at_loaddskf generated_46{};
    out.push_back(&generated_46);
    static const formats::at_mirage_snx generated_47{};
    out.push_back(&generated_47);
    static const formats::at_moof generated_48{};
    out.push_back(&generated_48);
    static const formats::at_msa generated_49{};
    out.push_back(&generated_49);
    static const formats::at_nufx generated_50{};
    out.push_back(&generated_50);
    static const formats::at_ofs generated_51{};
    out.push_back(&generated_51);
    static const formats::at_pdi generated_52{};
    out.push_back(&generated_52);
    static const formats::at_prodos generated_53{};
    out.push_back(&generated_53);
    static const formats::at_qrst generated_54{};
    out.push_back(&generated_54);
    static const formats::at_raw_disk_image generated_55{};
    out.push_back(&generated_55);
    static const formats::at_rim generated_56{};
    out.push_back(&generated_56);
    static const formats::at_sabdu generated_57{};
    out.push_back(&generated_57);
    static const formats::at_scp generated_58{};
    out.push_back(&generated_58);
    static const formats::at_st generated_59{};
    out.push_back(&generated_59);
    static const formats::at_stx generated_60{};
    out.push_back(&generated_60);
    static const formats::at_sxd generated_61{};
    out.push_back(&generated_61);
    static const formats::at_td0 generated_62{};
    out.push_back(&generated_62);
    static const formats::at_trd generated_63{};
    out.push_back(&generated_63);
    static const formats::at_trdos_fs generated_64{};
    out.push_back(&generated_64);
    static const formats::at_woz generated_65{};
    out.push_back(&generated_65);
    static const formats::at_wrp generated_66{};
    out.push_back(&generated_66);
    static const formats::at_xdf generated_67{};
    out.push_back(&generated_67);
    static const formats::at_xpack generated_68{};
    out.push_back(&generated_68);
    static const formats::at_zoom generated_69{};
    out.push_back(&generated_69);
    static const formats::sk_3o_chasm_the_rift generated_70{};
    out.push_back(&generated_70);
    static const formats::sk_4md generated_71{};
    out.push_back(&generated_71);
    static const formats::sk_4x4_off_road_racing_full_screen_graphic generated_72{};
    out.push_back(&generated_72);
    static const formats::sk_4x4_off_road_racing_graphic generated_73{};
    out.push_back(&generated_73);
    static const formats::sk_4x4_off_road_racing_sprite generated_74{};
    out.push_back(&generated_74);
    static const formats::sk_adlib_instrument generated_75{};
    out.push_back(&generated_75);
    static const formats::sk_adlib_instrument_bank generated_76{};
    out.push_back(&generated_76);
    static const formats::sk_adlib_midi generated_77{};
    out.push_back(&generated_77);
    static const formats::sk_adlib_sound_effect generated_78{};
    out.push_back(&generated_78);
    static const formats::sk_adlib_timbre_bank generated_79{};
    out.push_back(&generated_79);
    static const formats::sk_agos_vga generated_80{};
    out.push_back(&generated_80);
    static const formats::sk_aiff generated_81{};
    out.push_back(&generated_81);
    static const formats::sk_all_dogs_archive generated_82{};
    out.push_back(&generated_82);
    static const formats::sk_all_dogs_rle_compression generated_83{};
    out.push_back(&generated_83);
    static const formats::sk_amf generated_84{};
    out.push_back(&generated_84);
    static const formats::sk_ani_chasm_the_rift generated_85{};
    out.push_back(&generated_85);
    static const formats::sk_apogee_sound_system_timbre generated_86{};
    out.push_back(&generated_86);
    static const formats::sk_art_build generated_87{};
    out.push_back(&generated_87);
    static const formats::sk_artcraft_resource_file generated_88{};
    out.push_back(&generated_88);
    static const formats::sk_audiot generated_89{};
    out.push_back(&generated_89);
    static const formats::sk_b800_text generated_90{};
    out.push_back(&generated_90);
    static const formats::sk_battle_isle_history_line_library generated_91{};
    out.push_back(&generated_91);
    static const formats::sk_battle_isle_history_line_map generated_92{};
    out.push_back(&generated_92);
    static const formats::sk_bgi_stroked_font generated_93{};
    out.push_back(&generated_93);
    static const formats::sk_bin_chasm_the_rift generated_94{};
    out.push_back(&generated_94);
    static const formats::sk_bin_fury_of_the_furries generated_95{};
    out.push_back(&generated_95);
    static const formats::sk_blk_fury_of_the_furries generated_96{};
    out.push_back(&generated_96);
    static const formats::sk_bmc generated_97{};
    out.push_back(&generated_97);
    static const formats::sk_bnk_halloween_harry generated_98{};
    out.push_back(&generated_98);
    static const formats::sk_bodyworks_voyager_savegame generated_99{};
    out.push_back(&generated_99);
    static const formats::sk_borland_graphics_interface generated_100{};
    out.push_back(&generated_100);
    static const formats::sk_captain_comic_ii_dialog generated_101{};
    out.push_back(&generated_101);
    static const formats::sk_captain_comic_ii_map generated_102{};
    out.push_back(&generated_102);
    static const formats::sk_captain_comic_ii_sprite generated_103{};
    out.push_back(&generated_103);
    static const formats::sk_captain_comic_ii_tileset generated_104{};
    out.push_back(&generated_104);
    static const formats::sk_captain_comic_image generated_105{};
    out.push_back(&generated_105);
    static const formats::sk_captain_comic_map generated_106{};
    out.push_back(&generated_106);
    static const formats::sk_captain_comic_sprite generated_107{};
    out.push_back(&generated_107);
    static const formats::sk_captain_comic_tileset generated_108{};
    out.push_back(&generated_108);
    static const formats::sk_car_carnivores generated_109{};
    out.push_back(&generated_109);
    static const formats::sk_car_chasm_the_rift generated_110{};
    out.push_back(&generated_110);
    static const formats::sk_carmack_compression generated_111{};
    out.push_back(&generated_111);
    static const formats::sk_castle_adventure_data generated_112{};
    out.push_back(&generated_112);
    static const formats::sk_castles_ii_siege_and_conquest_cluster generated_113{};
    out.push_back(&generated_113);
    static const formats::sk_castles_ii_siege_and_conquest_save_game generated_114{};
    out.push_back(&generated_114);
    static const formats::sk_cat_mps_labs generated_115{};
    out.push_back(&generated_115);
    static const formats::sk_catacomb_highscore generated_116{};
    out.push_back(&generated_116);
    static const formats::sk_catacomb_map generated_117{};
    out.push_back(&generated_117);
    static const formats::sk_catacomb_savegame generated_118{};
    out.push_back(&generated_118);
    static const formats::sk_catacomb_tileset generated_119{};
    out.push_back(&generated_119);
    static const formats::sk_cc generated_120{};
    out.push_back(&generated_120);
    static const formats::sk_cc1 generated_121{};
    out.push_back(&generated_121);
    static const formats::sk_cdfm generated_122{};
    out.push_back(&generated_122);
    static const formats::sk_cel_image generated_123{};
    out.push_back(&generated_123);
    static const formats::sk_centurion_font generated_124{};
    out.push_back(&generated_124);
    static const formats::sk_cfg_f1_manager_professional generated_125{};
    out.push_back(&generated_125);
    static const formats::sk_cfg_jill_of_the_jungle generated_126{};
    out.push_back(&generated_126);
    static const formats::sk_cga_palette generated_127{};
    out.push_back(&generated_127);
    static const formats::sk_chasm_inf generated_128{};
    out.push_back(&generated_128);
    static const formats::sk_chr_halloween_harry generated_129{};
    out.push_back(&generated_129);
    static const formats::sk_cmf generated_130{};
    out.push_back(&generated_130);
    static const formats::sk_cmp generated_131{};
    out.push_back(&generated_131);
    static const formats::sk_command_and_conquer_mission generated_132{};
    out.push_back(&generated_132);
    static const formats::sk_command_and_conquer_red_alert_tileset generated_133{};
    out.push_back(&generated_133);
    static const formats::sk_command_and_conquer_red_alert_vortex_lookup_table generated_134{};
    out.push_back(&generated_134);
    static const formats::sk_command_and_conquer_tileset generated_135{};
    out.push_back(&generated_135);
    static const formats::sk_commander_keen_1_3_level generated_136{};
    out.push_back(&generated_136);
    static const formats::sk_commander_keen_1_3_score generated_137{};
    out.push_back(&generated_137);
    static const formats::sk_commander_keen_ega_header generated_138{};
    out.push_back(&generated_138);
    static const formats::sk_con generated_139{};
    out.push_back(&generated_139);
    static const formats::sk_cosmo_level generated_140{};
    out.push_back(&generated_140);
    static const formats::sk_cosmo_tileinfo generated_141{};
    out.push_back(&generated_141);
    static const formats::sk_cosmo_tileset generated_142{};
    out.push_back(&generated_142);
    static const formats::sk_cover_girl_strip_poker_font generated_143{};
    out.push_back(&generated_143);
    static const formats::sk_cover_girl_strip_poker_text generated_144{};
    out.push_back(&generated_144);
    static const formats::sk_crunched_screen_image generated_145{};
    out.push_back(&generated_145);
    static const formats::sk_crystal_caves_map generated_146{};
    out.push_back(&generated_146);
    static const formats::sk_crystal_caves_sound generated_147{};
    out.push_back(&generated_147);
    static const formats::sk_cur generated_148{};
    out.push_back(&generated_148);
    static const formats::sk_dangerous_dave_level generated_149{};
    out.push_back(&generated_149);
    static const formats::sk_dangerous_dave_tileset generated_150{};
    out.push_back(&generated_150);
    static const formats::sk_dark_ages_map generated_151{};
    out.push_back(&generated_151);
    static const formats::sk_dat_bullfrog generated_152{};
    out.push_back(&generated_152);
    static const formats::sk_dat_california_games_ii generated_153{};
    out.push_back(&generated_153);
    static const formats::sk_dat_centurion_defender_of_rome generated_154{};
    out.push_back(&generated_154);
    static const formats::sk_dat_dr_riptide generated_155{};
    out.push_back(&generated_155);
    static const formats::sk_dat_fury_of_the_furries generated_156{};
    out.push_back(&generated_156);
    static const formats::sk_dat_god_of_thunder generated_157{};
    out.push_back(&generated_157);
    static const formats::sk_dat_highway_hunter generated_158{};
    out.push_back(&generated_158);
    static const formats::sk_dat_hocus_pocus generated_159{};
    out.push_back(&generated_159);
    static const formats::sk_dat_hugo generated_160{};
    out.push_back(&generated_160);
    static const formats::sk_dat_monster_bash generated_161{};
    out.push_back(&generated_161);
    static const formats::sk_dat_mystic_towers generated_162{};
    out.push_back(&generated_162);
    static const formats::sk_dat_papyrus generated_163{};
    out.push_back(&generated_163);
    static const formats::sk_dat_sango_fighter generated_164{};
    out.push_back(&generated_164);
    static const formats::sk_dat_the_lost_vikings generated_165{};
    out.push_back(&generated_165);
    static const formats::sk_dat_wacky_wheels generated_166{};
    out.push_back(&generated_166);
    static const formats::sk_dat_zool generated_167{};
    out.push_back(&generated_167);
    static const formats::sk_dave_2_huffman_compression generated_168{};
    out.push_back(&generated_168);
    static const formats::sk_dave_2_intro generated_169{};
    out.push_back(&generated_169);
    static const formats::sk_dave_2_tileset generated_170{};
    out.push_back(&generated_170);
    static const formats::sk_dave_score generated_171{};
    out.push_back(&generated_171);
    static const formats::sk_ddici_graphics generated_172{};
    out.push_back(&generated_172);
    static const formats::sk_death_rally_bpa generated_173{};
    out.push_back(&generated_173);
    static const formats::sk_death_rally_bpk generated_174{};
    out.push_back(&generated_174);
    static const formats::sk_death_rally_cmf generated_175{};
    out.push_back(&generated_175);
    static const formats::sk_death_rally_haf generated_176{};
    out.push_back(&generated_176);
    static const formats::sk_del generated_177{};
    out.push_back(&generated_177);
    static const formats::sk_demo_fury_of_the_furries generated_178{};
    out.push_back(&generated_178);
    static const formats::sk_dlt generated_179{};
    out.push_back(&generated_179);
    static const formats::sk_dma generated_180{};
    out.push_back(&generated_180);
    static const formats::sk_dmp generated_181{};
    out.push_back(&generated_181);
    static const formats::sk_doofus_game_data generated_182{};
    out.push_back(&generated_182);
    static const formats::sk_dro generated_183{};
    out.push_back(&generated_183);
    static const formats::sk_dsik_config generated_184{};
    out.push_back(&generated_184);
    static const formats::sk_dsik_module generated_185{};
    out.push_back(&generated_185);
    static const formats::sk_dta_fury_of_the_furries generated_186{};
    out.push_back(&generated_186);
    static const formats::sk_duke_1_demo generated_187{};
    out.push_back(&generated_187);
    static const formats::sk_duke_1_level generated_188{};
    out.push_back(&generated_188);
    static const formats::sk_duke_nukem_3d_palette generated_189{};
    out.push_back(&generated_189);
    static const formats::sk_duke_nukem_ii_actor_info generated_190{};
    out.push_back(&generated_190);
    static const formats::sk_duke_nukem_ii_animation generated_191{};
    out.push_back(&generated_191);
    static const formats::sk_duke_nukem_ii_czone generated_192{};
    out.push_back(&generated_192);
    static const formats::sk_duke_nukem_ii_demo generated_193{};
    out.push_back(&generated_193);
    static const formats::sk_duke_nukem_ii_full_screen_images generated_194{};
    out.push_back(&generated_194);
    static const formats::sk_duke_nukem_ii_map generated_195{};
    out.push_back(&generated_195);
    static const formats::sk_duke_nukem_ii_misc_files generated_196{};
    out.push_back(&generated_196);
    static const formats::sk_duke_nukem_ii_palette generated_197{};
    out.push_back(&generated_197);
    static const formats::sk_dune_2000_font generated_198{};
    out.push_back(&generated_198);
    static const formats::sk_dungeons_of_the_unforgiven_character_creation_text generated_199{};
    out.push_back(&generated_199);
    static const formats::sk_dungeons_of_the_unforgiven_player_character generated_200{};
    out.push_back(&generated_200);
    static const formats::sk_dynamix_font_v1 generated_201{};
    out.push_back(&generated_201);
    static const formats::sk_dynamix_font_v2_v3 generated_202{};
    out.push_back(&generated_202);
    static const formats::sk_dynamix_font_v4_v5 generated_203{};
    out.push_back(&generated_203);
    static const formats::sk_dynamix_font_v6 generated_204{};
    out.push_back(&generated_204);
    static const formats::sk_ega_palette generated_205{};
    out.push_back(&generated_205);
    static const formats::sk_egagraph generated_206{};
    out.push_back(&generated_206);
    static const formats::sk_epf generated_207{};
    out.push_back(&generated_207);
    static const formats::sk_esi generated_208{};
    out.push_back(&generated_208);
    static const formats::sk_exe generated_209{};
    out.push_back(&generated_209);
    static const formats::sk_executioners_archive generated_210{};
    out.push_back(&generated_210);
    static const formats::sk_executioners_font generated_211{};
    out.push_back(&generated_211);
    static const formats::sk_executioners_rle generated_212{};
    out.push_back(&generated_212);
    static const formats::sk_executioners_sprite generated_213{};
    out.push_back(&generated_213);
    static const formats::sk_eye_of_the_beholder_palette generated_214{};
    out.push_back(&generated_214);
    static const formats::sk_eye_of_the_beholder_save_game generated_215{};
    out.push_back(&generated_215);
    static const formats::sk_eye_of_the_beholder_vcn generated_216{};
    out.push_back(&generated_216);
    static const formats::sk_eye_of_the_beholder_vmp generated_217{};
    out.push_back(&generated_217);
    static const formats::sk_family_feud_question generated_218{};
    out.push_back(&generated_218);
    static const formats::sk_family_feud_question_flag generated_219{};
    out.push_back(&generated_219);
    static const formats::sk_family_feud_save_game generated_220{};
    out.push_back(&generated_220);
    static const formats::sk_flic generated_221{};
    out.push_back(&generated_221);
    static const formats::sk_gamedat_fury_of_the_furries generated_222{};
    out.push_back(&generated_222);
    static const formats::sk_gamemaps generated_223{};
    out.push_back(&generated_223);
    static const formats::sk_gem_font generated_224{};
    out.push_back(&generated_224);
    static const formats::sk_glb_galactix generated_225{};
    out.push_back(&generated_225);
    static const formats::sk_glb_raptor generated_226{};
    out.push_back(&generated_226);
    static const formats::sk_global_timbre_library generated_227{};
    out.push_back(&generated_227);
    static const formats::sk_gmf_halloween_harry generated_228{};
    out.push_back(&generated_228);
    static const formats::sk_god_of_thunder_level generated_229{};
    out.push_back(&generated_229);
    static const formats::sk_god_of_thunder_music generated_230{};
    out.push_back(&generated_230);
    static const formats::sk_god_of_thunder_tileset generated_231{};
    out.push_back(&generated_231);
    static const formats::sk_graphics_interchange generated_232{};
    out.push_back(&generated_232);
    static const formats::sk_grp generated_233{};
    out.push_back(&generated_233);
    static const formats::sk_gx2 generated_234{};
    out.push_back(&generated_234);
    static const formats::sk_gx_library generated_235{};
    out.push_back(&generated_235);
    static const formats::sk_halloween_harry_dialogue generated_236{};
    out.push_back(&generated_236);
    static const formats::sk_heretic_executable generated_237{};
    out.push_back(&generated_237);
    static const formats::sk_heroquest_exe_file generated_238{};
    out.push_back(&generated_238);
    static const formats::sk_heroquest_quest generated_239{};
    out.push_back(&generated_239);
    static const formats::sk_heroquest_savegame generated_240{};
    out.push_back(&generated_240);
    static const formats::sk_hi_octane_texture_atlas generated_241{};
    out.push_back(&generated_241);
    static const formats::sk_hi_zzt generated_242{};
    out.push_back(&generated_242);
    static const formats::sk_hocus_pocus_image generated_243{};
    out.push_back(&generated_243);
    static const formats::sk_hocus_pocus_map generated_244{};
    out.push_back(&generated_244);
    static const formats::sk_hocus_pocus_palette generated_245{};
    out.push_back(&generated_245);
    static const formats::sk_hocus_pocus_sfx generated_246{};
    out.push_back(&generated_246);
    static const formats::sk_hocus_pocus_sprite generated_247{};
    out.push_back(&generated_247);
    static const formats::sk_hocus_pocus_text generated_248{};
    out.push_back(&generated_248);
    static const formats::sk_hog generated_249{};
    out.push_back(&generated_249);
    static const formats::sk_homebrew_file_folder generated_250{};
    out.push_back(&generated_250);
    static const formats::sk_hs_major_stryker generated_251{};
    out.push_back(&generated_251);
    static const formats::sk_hsb_halloween_harry generated_252{};
    out.push_back(&generated_252);
    static const formats::sk_huffman_compression generated_253{};
    out.push_back(&generated_253);
    static const formats::sk_hugo_map generated_254{};
    out.push_back(&generated_254);
    static const formats::sk_human_machine_interfaces_midi generated_255{};
    out.push_back(&generated_255);
    static const formats::sk_ibk generated_256{};
    out.push_back(&generated_256);
    static const formats::sk_ico_halloween_harry generated_257{};
    out.push_back(&generated_257);
    static const formats::sk_id_software_rlew_compression generated_258{};
    out.push_back(&generated_258);
    static const formats::sk_imf generated_259{};
    out.push_back(&generated_259);
    static const formats::sk_img_meen generated_260{};
    out.push_back(&generated_260);
    static const formats::sk_imm_fury_of_the_furries generated_261{};
    out.push_back(&generated_261);
    static const formats::sk_ims generated_262{};
    out.push_back(&generated_262);
    static const formats::sk_indy_500_library generated_263{};
    out.push_back(&generated_263);
    static const formats::sk_ins_halloween_harry generated_264{};
    out.push_back(&generated_264);
    static const formats::sk_int_33_graphics_pointer_shape generated_265{};
    out.push_back(&generated_265);
    static const formats::sk_inverse_frequency_sound generated_266{};
    out.push_back(&generated_266);
    static const formats::sk_isle_of_the_dead_font generated_267{};
    out.push_back(&generated_267);
    static const formats::sk_jam generated_268{};
    out.push_back(&generated_268);
    static const formats::sk_jazz_2_music generated_269{};
    out.push_back(&generated_269);
    static const formats::sk_jazz_jackrabbit_bonus generated_270{};
    out.push_back(&generated_270);
    static const formats::sk_jazz_jackrabbit_bonusmap generated_271{};
    out.push_back(&generated_271);
    static const formats::sk_jazz_jackrabbit_cutscene generated_272{};
    out.push_back(&generated_272);
    static const formats::sk_jazz_jackrabbit_demo generated_273{};
    out.push_back(&generated_273);
    static const formats::sk_jazz_jackrabbit_font generated_274{};
    out.push_back(&generated_274);
    static const formats::sk_jazz_jackrabbit_map generated_275{};
    out.push_back(&generated_275);
    static const formats::sk_jazz_jackrabbit_menu generated_276{};
    out.push_back(&generated_276);
    static const formats::sk_jazz_jackrabbit_panel generated_277{};
    out.push_back(&generated_277);
    static const formats::sk_jazz_jackrabbit_planet generated_278{};
    out.push_back(&generated_278);
    static const formats::sk_jazz_jackrabbit_rle_compression generated_279{};
    out.push_back(&generated_279);
    static const formats::sk_jazz_jackrabbit_saved_game generated_280{};
    out.push_back(&generated_280);
    static const formats::sk_jazz_jackrabbit_score generated_281{};
    out.push_back(&generated_281);
    static const formats::sk_jazz_jackrabbit_sound generated_282{};
    out.push_back(&generated_282);
    static const formats::sk_jazz_jackrabbit_sprite generated_283{};
    out.push_back(&generated_283);
    static const formats::sk_jazz_jackrabbit_tile generated_284{};
    out.push_back(&generated_284);
    static const formats::sk_jill_of_the_jungle_map generated_285{};
    out.push_back(&generated_285);
    static const formats::sk_joesnd generated_286{};
    out.push_back(&generated_286);
    static const formats::sk_karl_morton_music generated_287{};
    out.push_back(&generated_287);
    static const formats::sk_keen_1_3_rle_compression generated_288{};
    out.push_back(&generated_288);
    static const formats::sk_keen_1_3_saved_game generated_289{};
    out.push_back(&generated_289);
    static const formats::sk_kings_bounty_graphics generated_290{};
    out.push_back(&generated_290);
    static const formats::sk_kings_bounty_map generated_291{};
    out.push_back(&generated_291);
    static const formats::sk_kings_bounty_music generated_292{};
    out.push_back(&generated_292);
    static const formats::sk_kings_bounty_saved_game generated_293{};
    out.push_back(&generated_293);
    static const formats::sk_kings_of_the_beach_font generated_294{};
    out.push_back(&generated_294);
    static const formats::sk_kings_of_the_beach_pak generated_295{};
    out.push_back(&generated_295);
    static const formats::sk_klm generated_296{};
    out.push_back(&generated_296);
    static const formats::sk_kmd_fury_of_the_furries generated_297{};
    out.push_back(&generated_297);
    static const formats::sk_knowledge_dynamics_lzw_compressor generated_298{};
    out.push_back(&generated_298);
    static const formats::sk_kort_bmp generated_299{};
    out.push_back(&generated_299);
    static const formats::sk_kort_font generated_300{};
    out.push_back(&generated_300);
    static const formats::sk_kort_image generated_301{};
    out.push_back(&generated_301);
    static const formats::sk_kort_sound_archive generated_302{};
    out.push_back(&generated_302);
    static const formats::sk_kris_music_system generated_303{};
    out.push_back(&generated_303);
    static const formats::sk_kris_music_system_voice generated_304{};
    out.push_back(&generated_304);
    static const formats::sk_kvx_build generated_305{};
    out.push_back(&generated_305);
    static const formats::sk_lang_txt_fury_of_the_furries generated_306{};
    out.push_back(&generated_306);
    static const formats::sk_lbm generated_307{};
    out.push_back(&generated_307);
    static const formats::sk_lbr generated_308{};
    out.push_back(&generated_308);
    static const formats::sk_lbx generated_309{};
    out.push_back(&generated_309);
    static const formats::sk_legend_of_seven_paladins_3d_archive generated_310{};
    out.push_back(&generated_310);
    static const formats::sk_lib_electronic_arts generated_311{};
    out.push_back(&generated_311);
    static const formats::sk_lib_mythos_software generated_312{};
    out.push_back(&generated_312);
    static const formats::sk_linear_executable_lx_le generated_313{};
    out.push_back(&generated_313);
    static const formats::sk_lion_king_level generated_314{};
    out.push_back(&generated_314);
    static const formats::sk_lmh_lmo_fury_of_the_furries generated_315{};
    out.push_back(&generated_315);
    static const formats::sk_lpcm generated_316{};
    out.push_back(&generated_316);
    static const formats::sk_lzss_compression generated_317{};
    out.push_back(&generated_317);
    static const formats::sk_lzw_compression generated_318{};
    out.push_back(&generated_318);
    static const formats::sk_m generated_319{};
    out.push_back(&generated_319);
    static const formats::sk_major_stryker_level generated_320{};
    out.push_back(&generated_320);
    static const formats::sk_major_stryker_save_game generated_321{};
    out.push_back(&generated_321);
    static const formats::sk_major_stryker_text generated_322{};
    out.push_back(&generated_322);
    static const formats::sk_major_stryker_tileset generated_323{};
    out.push_back(&generated_323);
    static const formats::sk_map_build generated_324{};
    out.push_back(&generated_324);
    static const formats::sk_map_shadowcaster generated_325{};
    out.push_back(&generated_325);
    static const formats::sk_mat generated_326{};
    out.push_back(&generated_326);
    static const formats::sk_mch generated_327{};
    out.push_back(&generated_327);
    static const formats::sk_mdi generated_328{};
    out.push_back(&generated_328);
    static const formats::sk_megatech_vol generated_329{};
    out.push_back(&generated_329);
    static const formats::sk_messages_fury_of_the_furries generated_330{};
    out.push_back(&generated_330);
    static const formats::sk_microsoft_basic_mml generated_331{};
    out.push_back(&generated_331);
    static const formats::sk_microsoft_bitmap_font generated_332{};
    out.push_back(&generated_332);
    static const formats::sk_microsoft_exepack generated_333{};
    out.push_back(&generated_333);
    static const formats::sk_microsoft_vector_font generated_334{};
    out.push_back(&generated_334);
    static const formats::sk_mid generated_335{};
    out.push_back(&generated_335);
    static const formats::sk_miscellaneous_wacky_wheels_file generated_336{};
    out.push_back(&generated_336);
    static const formats::sk_mix_westwood generated_337{};
    out.push_back(&generated_337);
    static const formats::sk_mod generated_338{};
    out.push_back(&generated_338);
    static const formats::sk_monster_bash_level generated_339{};
    out.push_back(&generated_339);
    static const formats::sk_monster_bash_saved_game generated_340{};
    out.push_back(&generated_340);
    static const formats::sk_monster_bash_sprite generated_341{};
    out.push_back(&generated_341);
    static const formats::sk_monster_bash_tileset generated_342{};
    out.push_back(&generated_342);
    static const formats::sk_moraff_help_file generated_343{};
    out.push_back(&generated_343);
    static const formats::sk_moraff_monster_map generated_344{};
    out.push_back(&generated_344);
    static const formats::sk_mus generated_345{};
    out.push_back(&generated_345);
    static const formats::sk_mystic_towers_pc_speaker_sound generated_346{};
    out.push_back(&generated_346);
    static const formats::sk_mystic_towers_sprite generated_347{};
    out.push_back(&generated_347);
    static const formats::sk_nnv generated_348{};
    out.push_back(&generated_348);
    static const formats::sk_nomad_3d_model generated_349{};
    out.push_back(&generated_349);
    static const formats::sk_nomad_sound generated_350{};
    out.push_back(&generated_350);
    static const formats::sk_nomad_text generated_351{};
    out.push_back(&generated_351);
    static const formats::sk_nova generated_352{};
    out.push_back(&generated_352);
    static const formats::sk_op2_bank generated_353{};
    out.push_back(&generated_353);
    static const formats::sk_oregon_trail_dialogue generated_354{};
    out.push_back(&generated_354);
    static const formats::sk_oregon_trail_high_scores generated_355{};
    out.push_back(&generated_355);
    static const formats::sk_oregon_trail_joystick_calibration generated_356{};
    out.push_back(&generated_356);
    static const formats::sk_oregon_trail_save_game generated_357{};
    out.push_back(&generated_357);
    static const formats::sk_oregon_trail_tombstones generated_358{};
    out.push_back(&generated_358);
    static const formats::sk_paganitzu_graphics generated_359{};
    out.push_back(&generated_359);
    static const formats::sk_paganitzu_level generated_360{};
    out.push_back(&generated_360);
    static const formats::sk_pak_the_learning_company generated_361{};
    out.push_back(&generated_361);
    static const formats::sk_pak_westwood generated_362{};
    out.push_back(&generated_362);
    static const formats::sk_papyrus_palette generated_363{};
    out.push_back(&generated_363);
    static const formats::sk_pcx generated_364{};
    out.push_back(&generated_364);
    static const formats::sk_pcx_library generated_365{};
    out.push_back(&generated_365);
    static const formats::sk_pharaohs_tomb_and_arctic_adventure_fullscreen_image generated_366{};
    out.push_back(&generated_366);
    static const formats::sk_pic generated_367{};
    out.push_back(&generated_367);
    static const formats::sk_pic_sexonix generated_368{};
    out.push_back(&generated_368);
    static const formats::sk_pod generated_369{};
    out.push_back(&generated_369);
    static const formats::sk_pr2 generated_370{};
    out.push_back(&generated_370);
    static const formats::sk_pref_dat_witchaven generated_371{};
    out.push_back(&generated_371);
    static const formats::sk_prehistorik_level generated_372{};
    out.push_back(&generated_372);
    static const formats::sk_prographx_toolbox_tileset generated_373{};
    out.push_back(&generated_373);
    static const formats::sk_prot_fury_of_the_furries generated_374{};
    out.push_back(&generated_374);
    static const formats::sk_protracker_studio_module generated_375{};
    out.push_back(&generated_375);
    static const formats::sk_raptor_animated_graphics generated_376{};
    out.push_back(&generated_376);
    static const formats::sk_raptor_pic generated_377{};
    out.push_back(&generated_377);
    static const formats::sk_raptor_tileset generated_378{};
    out.push_back(&generated_378);
    static const formats::sk_raw_adlib generated_379{};
    out.push_back(&generated_379);
    static const formats::sk_raw_cga_data generated_380{};
    out.push_back(&generated_380);
    static const formats::sk_raw_ega_data generated_381{};
    out.push_back(&generated_381);
    static const formats::sk_raw_vga_image generated_382{};
    out.push_back(&generated_382);
    static const formats::sk_realms_of_chaos_level generated_383{};
    out.push_back(&generated_383);
    static const formats::sk_realms_of_chaos_masked_tileset generated_384{};
    out.push_back(&generated_384);
    static const formats::sk_realms_of_chaos_sprite generated_385{};
    out.push_back(&generated_385);
    static const formats::sk_realms_of_chaos_tileset generated_386{};
    out.push_back(&generated_386);
    static const formats::sk_res_boppin generated_387{};
    out.push_back(&generated_387);
    static const formats::sk_res_stellar_7 generated_388{};
    out.push_back(&generated_388);
    static const formats::sk_rescue_rover_saved_game generated_389{};
    out.push_back(&generated_389);
    static const formats::sk_rff generated_390{};
    out.push_back(&generated_390);
    static const formats::sk_rle_compression generated_391{};
    out.push_back(&generated_391);
    static const formats::sk_rob_northern_compression generated_392{};
    out.push_back(&generated_392);
    static const formats::sk_rol generated_393{};
    out.push_back(&generated_393);
    static const formats::sk_rol_image_archive generated_394{};
    out.push_back(&generated_394);
    static const formats::sk_rsc_battlestar generated_395{};
    out.push_back(&generated_395);
    static const formats::sk_rsc_f1_manager_professional generated_396{};
    out.push_back(&generated_396);
    static const formats::sk_rtl generated_397{};
    out.push_back(&generated_397);
    static const formats::sk_rts generated_398{};
    out.push_back(&generated_398);
    static const formats::sk_s3m generated_399{};
    out.push_back(&generated_399);
    static const formats::sk_sango_fighter_rlc_compression generated_400{};
    out.push_back(&generated_400);
    static const formats::sk_sav_hocus_pocus generated_401{};
    out.push_back(&generated_401);
    static const formats::sk_sbi generated_402{};
    out.push_back(&generated_402);
    static const formats::sk_secret_agent_level generated_403{};
    out.push_back(&generated_403);
    static const formats::sk_selectware_archive generated_404{};
    out.push_back(&generated_404);
    static const formats::sk_setup_dat_witchaven generated_405{};
    out.push_back(&generated_405);
    static const formats::sk_sha generated_406{};
    out.push_back(&generated_406);
    static const formats::sk_shadow_warrior_1993_beta_background_image generated_407{};
    out.push_back(&generated_407);
    static const formats::sk_shadow_warrior_1993_beta_image generated_408{};
    out.push_back(&generated_408);
    static const formats::sk_shaws_nightmare_archive generated_409{};
    out.push_back(&generated_409);
    static const formats::sk_skyroads_compression generated_410{};
    out.push_back(&generated_410);
    static const formats::sk_skyroads_image generated_411{};
    out.push_back(&generated_411);
    static const formats::sk_skyroads_level generated_412{};
    out.push_back(&generated_412);
    static const formats::sk_skyroads_save_game generated_413{};
    out.push_back(&generated_413);
    static const formats::sk_slb generated_414{};
    out.push_back(&generated_414);
    static const formats::sk_smacker_video generated_415{};
    out.push_back(&generated_415);
    static const formats::sk_softdisk_library generated_416{};
    out.push_back(&generated_416);
    static const formats::sk_softmax_resource_file generated_417{};
    out.push_back(&generated_417);
    static const formats::sk_solar_winds_sprites generated_418{};
    out.push_back(&generated_418);
    static const formats::sk_sop generated_419{};
    out.push_back(&generated_419);
    static const formats::sk_space_crusade_savegame generated_420{};
    out.push_back(&generated_420);
    static const formats::sk_space_quest_v_font generated_421{};
    out.push_back(&generated_421);
    static const formats::sk_ssp generated_422{};
    out.push_back(&generated_422);
    static const formats::sk_stargunner_sprites generated_423{};
    out.push_back(&generated_423);
    static const formats::sk_stp generated_424{};
    out.push_back(&generated_424);
    static const formats::sk_super_street_fighter_ii_turbo_movie generated_425{};
    out.push_back(&generated_425);
    static const formats::sk_super_street_fighter_ii_turbo_sprite generated_426{};
    out.push_back(&generated_426);
    static const formats::sk_swords_of_glass_fortune generated_427{};
    out.push_back(&generated_427);
    static const formats::sk_swords_of_glass_graphic generated_428{};
    out.push_back(&generated_428);
    static const formats::sk_swords_of_glass_info generated_429{};
    out.push_back(&generated_429);
    static const formats::sk_swords_of_glass_map generated_430{};
    out.push_back(&generated_430);
    static const formats::sk_swords_of_glass_message generated_431{};
    out.push_back(&generated_431);
    static const formats::sk_swords_of_glass_monster generated_432{};
    out.push_back(&generated_432);
    static const formats::sk_swords_of_glass_names generated_433{};
    out.push_back(&generated_433);
    static const formats::sk_swords_of_glass_people generated_434{};
    out.push_back(&generated_434);
    static const formats::sk_swords_of_glass_puzzle generated_435{};
    out.push_back(&generated_435);
    static const formats::sk_swords_of_glass_vault generated_436{};
    out.push_back(&generated_436);
    static const formats::sk_tbsa_music generated_437{};
    out.push_back(&generated_437);
    static const formats::sk_the_blues_brothers_huffman_compression generated_438{};
    out.push_back(&generated_438);
    static const formats::sk_the_blues_brothers_map generated_439{};
    out.push_back(&generated_439);
    static const formats::sk_the_blues_brothers_sprite generated_440{};
    out.push_back(&generated_440);
    static const formats::sk_the_incredible_machine_2_3_anm_file generated_441{};
    out.push_back(&generated_441);
    static const formats::sk_the_incredible_machine_image generated_442{};
    out.push_back(&generated_442);
    static const formats::sk_the_incredible_machine_level generated_443{};
    out.push_back(&generated_443);
    static const formats::sk_tim_resource generated_444{};
    out.push_back(&generated_444);
    static const formats::sk_titus_interactive_sqz_compression generated_445{};
    out.push_back(&generated_445);
    static const formats::sk_top_halloween_harry generated_446{};
    out.push_back(&generated_446);
    static const formats::sk_transylvania_font generated_447{};
    out.push_back(&generated_447);
    static const formats::sk_treasure_mountain_panning_image generated_448{};
    out.push_back(&generated_448);
    static const formats::sk_treasure_mountain_save_file generated_449{};
    out.push_back(&generated_449);
    static const formats::sk_trugg_level generated_450{};
    out.push_back(&generated_450);
    static const formats::sk_ultima_i_full_screen_graphic generated_451{};
    out.push_back(&generated_451);
    static const formats::sk_ultima_i_map generated_452{};
    out.push_back(&generated_452);
    static const formats::sk_ultima_i_save_game generated_453{};
    out.push_back(&generated_453);
    static const formats::sk_ultima_i_tile_graphic generated_454{};
    out.push_back(&generated_454);
    static const formats::sk_ultima_i_town_map generated_455{};
    out.push_back(&generated_455);
    static const formats::sk_ultima_ii_dungeon generated_456{};
    out.push_back(&generated_456);
    static const formats::sk_ultima_ii_map generated_457{};
    out.push_back(&generated_457);
    static const formats::sk_ultima_ii_talk generated_458{};
    out.push_back(&generated_458);
    static const formats::sk_vga_palette generated_459{};
    out.push_back(&generated_459);
    static const formats::sk_vgfm_graphics generated_460{};
    out.push_back(&generated_460);
    static const formats::sk_vgfm_level generated_461{};
    out.push_back(&generated_461);
    static const formats::sk_vgfm_raw_tileset generated_462{};
    out.push_back(&generated_462);
    static const formats::sk_vgfm_save generated_463{};
    out.push_back(&generated_463);
    static const formats::sk_vgfm_screen generated_464{};
    out.push_back(&generated_464);
    static const formats::sk_vgfm_tileset generated_465{};
    out.push_back(&generated_465);
    static const formats::sk_viacom_new_media_graphics_file generated_466{};
    out.push_back(&generated_466);
    static const formats::sk_visage generated_467{};
    out.push_back(&generated_467);
    static const formats::sk_visage_animation generated_468{};
    out.push_back(&generated_468);
    static const formats::sk_voc generated_469{};
    out.push_back(&generated_469);
    static const formats::sk_wacky_wheels_configuration generated_470{};
    out.push_back(&generated_470);
    static const formats::sk_wacky_wheels_high_score_files generated_471{};
    out.push_back(&generated_471);
    static const formats::sk_wacky_wheels_track generated_472{};
    out.push_back(&generated_472);
    static const formats::sk_wad generated_473{};
    out.push_back(&generated_473);
    static const formats::sk_wasteland_pic generated_474{};
    out.push_back(&generated_474);
    static const formats::sk_wav generated_475{};
    out.push_back(&generated_475);
    static const formats::sk_westwood_aud generated_476{};
    out.push_back(&generated_476);
    static const formats::sk_westwood_bitfont generated_477{};
    out.push_back(&generated_477);
    static const formats::sk_westwood_cmp generated_478{};
    out.push_back(&generated_478);
    static const formats::sk_westwood_cps generated_479{};
    out.push_back(&generated_479);
    static const formats::sk_westwood_fading_table generated_480{};
    out.push_back(&generated_480);
    static const formats::sk_westwood_font_v1 generated_481{};
    out.push_back(&generated_481);
    static const formats::sk_westwood_font_v2 generated_482{};
    out.push_back(&generated_482);
    static const formats::sk_westwood_font_v3 generated_483{};
    out.push_back(&generated_483);
    static const formats::sk_westwood_font_v4 generated_484{};
    out.push_back(&generated_484);
    static const formats::sk_westwood_lcw generated_485{};
    out.push_back(&generated_485);
    static const formats::sk_westwood_lzw_12 generated_486{};
    out.push_back(&generated_486);
    static const formats::sk_westwood_lzw_14 generated_487{};
    out.push_back(&generated_487);
    static const formats::sk_westwood_rle generated_488{};
    out.push_back(&generated_488);
    static const formats::sk_westwood_rle_zero generated_489{};
    out.push_back(&generated_489);
    static const formats::sk_westwood_shp_dune_ii generated_490{};
    out.push_back(&generated_490);
    static const formats::sk_westwood_shp_lands_of_lore generated_491{};
    out.push_back(&generated_491);
    static const formats::sk_westwood_shp_td generated_492{};
    out.push_back(&generated_492);
    static const formats::sk_westwood_shp_ts generated_493{};
    out.push_back(&generated_493);
    static const formats::sk_westwood_unicode_bitfont generated_494{};
    out.push_back(&generated_494);
    static const formats::sk_westwood_wsa generated_495{};
    out.push_back(&generated_495);
    static const formats::sk_westwood_xor_delta generated_496{};
    out.push_back(&generated_496);
    static const formats::sk_wing_commander_save_game generated_497{};
    out.push_back(&generated_497);
    static const formats::sk_word_rescue_demo generated_498{};
    out.push_back(&generated_498);
    static const formats::sk_word_rescue_highscore generated_499{};
    out.push_back(&generated_499);
    static const formats::sk_word_rescue_level generated_500{};
    out.push_back(&generated_500);
    static const formats::sk_word_rescue_saved_game generated_501{};
    out.push_back(&generated_501);
    static const formats::sk_xmi generated_502{};
    out.push_back(&generated_502);
    static const formats::sk_zlib_compression generated_503{};
    out.push_back(&generated_503);
    static const formats::sk_zone_66_compression generated_504{};
    out.push_back(&generated_504);
    static const formats::sk_zone_66_high_scores generated_505{};
    out.push_back(&generated_505);
    static const formats::sk_zone_66_level generated_506{};
    out.push_back(&generated_506);
    static const formats::sk_zone_66_tileset generated_507{};
    out.push_back(&generated_507);
    static const formats::sk_zzt generated_508{};
    out.push_back(&generated_508);
}

} /* namespace dumpfloppy */

#endif /* DUMPFLOPPY_FORMATS_GENERATED_FORMATS_H */
