/**
 * @file generated_payload.h
 * @brief Auto-generated payload format classes.
 * @warning Generated by scripts/gen_format_registry.py — do not edit.
 */
#ifndef DUMPFLOPPY_FORMATS_GENERATED_PAYLOAD_H
#define DUMPFLOPPY_FORMATS_GENERATED_PAYLOAD_H

#include "dumpfloppy/format.h"

#include "dumpfloppy/formats/shikadi/sk_3o_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_4md.h"
#include "dumpfloppy/formats/shikadi/sk_4x4_off_road_racing_full_screen_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_4x4_off_road_racing_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_4x4_off_road_racing_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_instrument.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_instrument_bank.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_midi.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_sound_effect.h"
#include "dumpfloppy/formats/shikadi/sk_adlib_timbre_bank.h"
#include "dumpfloppy/formats/shikadi/sk_agos_vga.h"
#include "dumpfloppy/formats/shikadi/sk_aiff.h"
#include "dumpfloppy/formats/shikadi/sk_all_dogs_archive.h"
#include "dumpfloppy/formats/shikadi/sk_all_dogs_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_amf.h"
#include "dumpfloppy/formats/shikadi/sk_ani_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_apogee_sound_system_timbre.h"
#include "dumpfloppy/formats/shikadi/sk_art_build.h"
#include "dumpfloppy/formats/shikadi/sk_artcraft_resource_file.h"
#include "dumpfloppy/formats/shikadi/sk_audiot.h"
#include "dumpfloppy/formats/shikadi/sk_b800_text.h"
#include "dumpfloppy/formats/shikadi/sk_battle_isle_history_line_library.h"
#include "dumpfloppy/formats/shikadi/sk_battle_isle_history_line_map.h"
#include "dumpfloppy/formats/shikadi/sk_bgi_stroked_font.h"
#include "dumpfloppy/formats/shikadi/sk_bin_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_bin_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_blk_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_bmc.h"
#include "dumpfloppy/formats/shikadi/sk_bnk_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_bodyworks_voyager_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_borland_graphics_interface.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_dialog.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_map.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_ii_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_image.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_map.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_captain_comic_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_car_carnivores.h"
#include "dumpfloppy/formats/shikadi/sk_car_chasm_the_rift.h"
#include "dumpfloppy/formats/shikadi/sk_carmack_compression.h"
#include "dumpfloppy/formats/shikadi/sk_castle_adventure_data.h"
#include "dumpfloppy/formats/shikadi/sk_castles_ii_siege_and_conquest_cluster.h"
#include "dumpfloppy/formats/shikadi/sk_castles_ii_siege_and_conquest_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_cat_mps_labs.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_highscore.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_map.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_catacomb_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_cc.h"
#include "dumpfloppy/formats/shikadi/sk_cc1.h"
#include "dumpfloppy/formats/shikadi/sk_cdfm.h"
#include "dumpfloppy/formats/shikadi/sk_cel_image.h"
#include "dumpfloppy/formats/shikadi/sk_centurion_font.h"
#include "dumpfloppy/formats/shikadi/sk_cfg_f1_manager_professional.h"
#include "dumpfloppy/formats/shikadi/sk_cfg_jill_of_the_jungle.h"
#include "dumpfloppy/formats/shikadi/sk_cga_palette.h"
#include "dumpfloppy/formats/shikadi/sk_chasm_inf.h"
#include "dumpfloppy/formats/shikadi/sk_chr_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_cmf.h"
#include "dumpfloppy/formats/shikadi/sk_cmp.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_mission.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_red_alert_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_red_alert_vortex_lookup_table.h"
#include "dumpfloppy/formats/shikadi/sk_command_and_conquer_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_commander_keen_1_3_level.h"
#include "dumpfloppy/formats/shikadi/sk_commander_keen_1_3_score.h"
#include "dumpfloppy/formats/shikadi/sk_commander_keen_ega_header.h"
#include "dumpfloppy/formats/shikadi/sk_con.h"
#include "dumpfloppy/formats/shikadi/sk_cosmo_level.h"
#include "dumpfloppy/formats/shikadi/sk_cosmo_tileinfo.h"
#include "dumpfloppy/formats/shikadi/sk_cosmo_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_cover_girl_strip_poker_font.h"
#include "dumpfloppy/formats/shikadi/sk_cover_girl_strip_poker_text.h"
#include "dumpfloppy/formats/shikadi/sk_crunched_screen_image.h"
#include "dumpfloppy/formats/shikadi/sk_crystal_caves_map.h"
#include "dumpfloppy/formats/shikadi/sk_crystal_caves_sound.h"
#include "dumpfloppy/formats/shikadi/sk_cur.h"
#include "dumpfloppy/formats/shikadi/sk_dangerous_dave_level.h"
#include "dumpfloppy/formats/shikadi/sk_dangerous_dave_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_dark_ages_map.h"
#include "dumpfloppy/formats/shikadi/sk_dat_bullfrog.h"
#include "dumpfloppy/formats/shikadi/sk_dat_california_games_ii.h"
#include "dumpfloppy/formats/shikadi/sk_dat_centurion_defender_of_rome.h"
#include "dumpfloppy/formats/shikadi/sk_dat_dr_riptide.h"
#include "dumpfloppy/formats/shikadi/sk_dat_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_dat_god_of_thunder.h"
#include "dumpfloppy/formats/shikadi/sk_dat_highway_hunter.h"
#include "dumpfloppy/formats/shikadi/sk_dat_hocus_pocus.h"
#include "dumpfloppy/formats/shikadi/sk_dat_hugo.h"
#include "dumpfloppy/formats/shikadi/sk_dat_monster_bash.h"
#include "dumpfloppy/formats/shikadi/sk_dat_mystic_towers.h"
#include "dumpfloppy/formats/shikadi/sk_dat_papyrus.h"
#include "dumpfloppy/formats/shikadi/sk_dat_sango_fighter.h"
#include "dumpfloppy/formats/shikadi/sk_dat_the_lost_vikings.h"
#include "dumpfloppy/formats/shikadi/sk_dat_wacky_wheels.h"
#include "dumpfloppy/formats/shikadi/sk_dat_zool.h"
#include "dumpfloppy/formats/shikadi/sk_dave_2_huffman_compression.h"
#include "dumpfloppy/formats/shikadi/sk_dave_2_intro.h"
#include "dumpfloppy/formats/shikadi/sk_dave_2_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_dave_score.h"
#include "dumpfloppy/formats/shikadi/sk_ddici_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_bpa.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_bpk.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_cmf.h"
#include "dumpfloppy/formats/shikadi/sk_death_rally_haf.h"
#include "dumpfloppy/formats/shikadi/sk_del.h"
#include "dumpfloppy/formats/shikadi/sk_demo_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_dlt.h"
#include "dumpfloppy/formats/shikadi/sk_dma.h"
#include "dumpfloppy/formats/shikadi/sk_dmp.h"
#include "dumpfloppy/formats/shikadi/sk_doofus_game_data.h"
#include "dumpfloppy/formats/shikadi/sk_dro.h"
#include "dumpfloppy/formats/shikadi/sk_dsik_config.h"
#include "dumpfloppy/formats/shikadi/sk_dsik_module.h"
#include "dumpfloppy/formats/shikadi/sk_dta_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_duke_1_demo.h"
#include "dumpfloppy/formats/shikadi/sk_duke_1_level.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_3d_palette.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_actor_info.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_animation.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_czone.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_demo.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_full_screen_images.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_map.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_misc_files.h"
#include "dumpfloppy/formats/shikadi/sk_duke_nukem_ii_palette.h"
#include "dumpfloppy/formats/shikadi/sk_dune_2000_font.h"
#include "dumpfloppy/formats/shikadi/sk_dungeons_of_the_unforgiven_character_creation_text.h"
#include "dumpfloppy/formats/shikadi/sk_dungeons_of_the_unforgiven_player_character.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v1.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v2_v3.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v4_v5.h"
#include "dumpfloppy/formats/shikadi/sk_dynamix_font_v6.h"
#include "dumpfloppy/formats/shikadi/sk_ega_palette.h"
#include "dumpfloppy/formats/shikadi/sk_egagraph.h"
#include "dumpfloppy/formats/shikadi/sk_epf.h"
#include "dumpfloppy/formats/shikadi/sk_esi.h"
#include "dumpfloppy/formats/shikadi/sk_exe.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_archive.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_font.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_rle.h"
#include "dumpfloppy/formats/shikadi/sk_executioners_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_palette.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_vcn.h"
#include "dumpfloppy/formats/shikadi/sk_eye_of_the_beholder_vmp.h"
#include "dumpfloppy/formats/shikadi/sk_family_feud_question.h"
#include "dumpfloppy/formats/shikadi/sk_family_feud_question_flag.h"
#include "dumpfloppy/formats/shikadi/sk_family_feud_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_flic.h"
#include "dumpfloppy/formats/shikadi/sk_gamedat_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_gamemaps.h"
#include "dumpfloppy/formats/shikadi/sk_gem_font.h"
#include "dumpfloppy/formats/shikadi/sk_glb_galactix.h"
#include "dumpfloppy/formats/shikadi/sk_glb_raptor.h"
#include "dumpfloppy/formats/shikadi/sk_global_timbre_library.h"
#include "dumpfloppy/formats/shikadi/sk_gmf_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_god_of_thunder_level.h"
#include "dumpfloppy/formats/shikadi/sk_god_of_thunder_music.h"
#include "dumpfloppy/formats/shikadi/sk_god_of_thunder_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_graphics_interchange.h"
#include "dumpfloppy/formats/shikadi/sk_grp.h"
#include "dumpfloppy/formats/shikadi/sk_gx2.h"
#include "dumpfloppy/formats/shikadi/sk_gx_library.h"
#include "dumpfloppy/formats/shikadi/sk_halloween_harry_dialogue.h"
#include "dumpfloppy/formats/shikadi/sk_heretic_executable.h"
#include "dumpfloppy/formats/shikadi/sk_heroquest_exe_file.h"
#include "dumpfloppy/formats/shikadi/sk_heroquest_quest.h"
#include "dumpfloppy/formats/shikadi/sk_heroquest_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_hi_octane_texture_atlas.h"
#include "dumpfloppy/formats/shikadi/sk_hi_zzt.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_image.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_map.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_palette.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_sfx.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_hocus_pocus_text.h"
#include "dumpfloppy/formats/shikadi/sk_hog.h"
#include "dumpfloppy/formats/shikadi/sk_homebrew_file_folder.h"
#include "dumpfloppy/formats/shikadi/sk_hs_major_stryker.h"
#include "dumpfloppy/formats/shikadi/sk_hsb_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_huffman_compression.h"
#include "dumpfloppy/formats/shikadi/sk_hugo_map.h"
#include "dumpfloppy/formats/shikadi/sk_human_machine_interfaces_midi.h"
#include "dumpfloppy/formats/shikadi/sk_ibk.h"
#include "dumpfloppy/formats/shikadi/sk_ico_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_id_software_rlew_compression.h"
#include "dumpfloppy/formats/shikadi/sk_imf.h"
#include "dumpfloppy/formats/shikadi/sk_img_meen.h"
#include "dumpfloppy/formats/shikadi/sk_imm_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_ims.h"
#include "dumpfloppy/formats/shikadi/sk_indy_500_library.h"
#include "dumpfloppy/formats/shikadi/sk_ins_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_int_33_graphics_pointer_shape.h"
#include "dumpfloppy/formats/shikadi/sk_inverse_frequency_sound.h"
#include "dumpfloppy/formats/shikadi/sk_isle_of_the_dead_font.h"
#include "dumpfloppy/formats/shikadi/sk_jam.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_2_music.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_bonus.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_bonusmap.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_cutscene.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_demo.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_font.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_map.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_menu.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_panel.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_planet.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_score.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_sound.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_jazz_jackrabbit_tile.h"
#include "dumpfloppy/formats/shikadi/sk_jill_of_the_jungle_map.h"
#include "dumpfloppy/formats/shikadi/sk_joesnd.h"
#include "dumpfloppy/formats/shikadi/sk_karl_morton_music.h"
#include "dumpfloppy/formats/shikadi/sk_keen_1_3_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_keen_1_3_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_map.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_music.h"
#include "dumpfloppy/formats/shikadi/sk_kings_bounty_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_kings_of_the_beach_font.h"
#include "dumpfloppy/formats/shikadi/sk_kings_of_the_beach_pak.h"
#include "dumpfloppy/formats/shikadi/sk_klm.h"
#include "dumpfloppy/formats/shikadi/sk_kmd_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_knowledge_dynamics_lzw_compressor.h"
#include "dumpfloppy/formats/shikadi/sk_kort_bmp.h"
#include "dumpfloppy/formats/shikadi/sk_kort_font.h"
#include "dumpfloppy/formats/shikadi/sk_kort_image.h"
#include "dumpfloppy/formats/shikadi/sk_kort_sound_archive.h"
#include "dumpfloppy/formats/shikadi/sk_kris_music_system.h"
#include "dumpfloppy/formats/shikadi/sk_kris_music_system_voice.h"
#include "dumpfloppy/formats/shikadi/sk_kvx_build.h"
#include "dumpfloppy/formats/shikadi/sk_lang_txt_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_lbm.h"
#include "dumpfloppy/formats/shikadi/sk_lbr.h"
#include "dumpfloppy/formats/shikadi/sk_lbx.h"
#include "dumpfloppy/formats/shikadi/sk_legend_of_seven_paladins_3d_archive.h"
#include "dumpfloppy/formats/shikadi/sk_lib_electronic_arts.h"
#include "dumpfloppy/formats/shikadi/sk_lib_mythos_software.h"
#include "dumpfloppy/formats/shikadi/sk_linear_executable_lx_le.h"
#include "dumpfloppy/formats/shikadi/sk_lion_king_level.h"
#include "dumpfloppy/formats/shikadi/sk_lmh_lmo_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_lpcm.h"
#include "dumpfloppy/formats/shikadi/sk_lzss_compression.h"
#include "dumpfloppy/formats/shikadi/sk_lzw_compression.h"
#include "dumpfloppy/formats/shikadi/sk_m.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_level.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_text.h"
#include "dumpfloppy/formats/shikadi/sk_major_stryker_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_map_build.h"
#include "dumpfloppy/formats/shikadi/sk_map_shadowcaster.h"
#include "dumpfloppy/formats/shikadi/sk_mat.h"
#include "dumpfloppy/formats/shikadi/sk_mch.h"
#include "dumpfloppy/formats/shikadi/sk_mdi.h"
#include "dumpfloppy/formats/shikadi/sk_megatech_vol.h"
#include "dumpfloppy/formats/shikadi/sk_messages_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_basic_mml.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_bitmap_font.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_exepack.h"
#include "dumpfloppy/formats/shikadi/sk_microsoft_vector_font.h"
#include "dumpfloppy/formats/shikadi/sk_mid.h"
#include "dumpfloppy/formats/shikadi/sk_miscellaneous_wacky_wheels_file.h"
#include "dumpfloppy/formats/shikadi/sk_mix_westwood.h"
#include "dumpfloppy/formats/shikadi/sk_mod.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_level.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_monster_bash_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_moraff_help_file.h"
#include "dumpfloppy/formats/shikadi/sk_moraff_monster_map.h"
#include "dumpfloppy/formats/shikadi/sk_mus.h"
#include "dumpfloppy/formats/shikadi/sk_mystic_towers_pc_speaker_sound.h"
#include "dumpfloppy/formats/shikadi/sk_mystic_towers_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_nnv.h"
#include "dumpfloppy/formats/shikadi/sk_nomad_3d_model.h"
#include "dumpfloppy/formats/shikadi/sk_nomad_sound.h"
#include "dumpfloppy/formats/shikadi/sk_nomad_text.h"
#include "dumpfloppy/formats/shikadi/sk_nova.h"
#include "dumpfloppy/formats/shikadi/sk_op2_bank.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_dialogue.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_high_scores.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_joystick_calibration.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_oregon_trail_tombstones.h"
#include "dumpfloppy/formats/shikadi/sk_paganitzu_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_paganitzu_level.h"
#include "dumpfloppy/formats/shikadi/sk_pak_the_learning_company.h"
#include "dumpfloppy/formats/shikadi/sk_pak_westwood.h"
#include "dumpfloppy/formats/shikadi/sk_papyrus_palette.h"
#include "dumpfloppy/formats/shikadi/sk_pcx.h"
#include "dumpfloppy/formats/shikadi/sk_pcx_library.h"
#include "dumpfloppy/formats/shikadi/sk_pharaohs_tomb_and_arctic_adventure_fullscreen_image.h"
#include "dumpfloppy/formats/shikadi/sk_pic.h"
#include "dumpfloppy/formats/shikadi/sk_pic_sexonix.h"
#include "dumpfloppy/formats/shikadi/sk_pod.h"
#include "dumpfloppy/formats/shikadi/sk_pr2.h"
#include "dumpfloppy/formats/shikadi/sk_pref_dat_witchaven.h"
#include "dumpfloppy/formats/shikadi/sk_prehistorik_level.h"
#include "dumpfloppy/formats/shikadi/sk_prographx_toolbox_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_prot_fury_of_the_furries.h"
#include "dumpfloppy/formats/shikadi/sk_protracker_studio_module.h"
#include "dumpfloppy/formats/shikadi/sk_raptor_animated_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_raptor_pic.h"
#include "dumpfloppy/formats/shikadi/sk_raptor_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_raw_adlib.h"
#include "dumpfloppy/formats/shikadi/sk_raw_cga_data.h"
#include "dumpfloppy/formats/shikadi/sk_raw_ega_data.h"
#include "dumpfloppy/formats/shikadi/sk_raw_vga_image.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_level.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_masked_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_realms_of_chaos_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_res_boppin.h"
#include "dumpfloppy/formats/shikadi/sk_res_stellar_7.h"
#include "dumpfloppy/formats/shikadi/sk_rescue_rover_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_rff.h"
#include "dumpfloppy/formats/shikadi/sk_rle_compression.h"
#include "dumpfloppy/formats/shikadi/sk_rob_northern_compression.h"
#include "dumpfloppy/formats/shikadi/sk_rol.h"
#include "dumpfloppy/formats/shikadi/sk_rol_image_archive.h"
#include "dumpfloppy/formats/shikadi/sk_rsc_battlestar.h"
#include "dumpfloppy/formats/shikadi/sk_rsc_f1_manager_professional.h"
#include "dumpfloppy/formats/shikadi/sk_rtl.h"
#include "dumpfloppy/formats/shikadi/sk_rts.h"
#include "dumpfloppy/formats/shikadi/sk_s3m.h"
#include "dumpfloppy/formats/shikadi/sk_sango_fighter_rlc_compression.h"
#include "dumpfloppy/formats/shikadi/sk_sav_hocus_pocus.h"
#include "dumpfloppy/formats/shikadi/sk_sbi.h"
#include "dumpfloppy/formats/shikadi/sk_secret_agent_level.h"
#include "dumpfloppy/formats/shikadi/sk_selectware_archive.h"
#include "dumpfloppy/formats/shikadi/sk_setup_dat_witchaven.h"
#include "dumpfloppy/formats/shikadi/sk_sha.h"
#include "dumpfloppy/formats/shikadi/sk_shadow_warrior_1993_beta_background_image.h"
#include "dumpfloppy/formats/shikadi/sk_shadow_warrior_1993_beta_image.h"
#include "dumpfloppy/formats/shikadi/sk_shaws_nightmare_archive.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_compression.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_image.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_level.h"
#include "dumpfloppy/formats/shikadi/sk_skyroads_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_slb.h"
#include "dumpfloppy/formats/shikadi/sk_smacker_video.h"
#include "dumpfloppy/formats/shikadi/sk_softdisk_library.h"
#include "dumpfloppy/formats/shikadi/sk_softmax_resource_file.h"
#include "dumpfloppy/formats/shikadi/sk_solar_winds_sprites.h"
#include "dumpfloppy/formats/shikadi/sk_sop.h"
#include "dumpfloppy/formats/shikadi/sk_space_crusade_savegame.h"
#include "dumpfloppy/formats/shikadi/sk_space_quest_v_font.h"
#include "dumpfloppy/formats/shikadi/sk_ssp.h"
#include "dumpfloppy/formats/shikadi/sk_stargunner_sprites.h"
#include "dumpfloppy/formats/shikadi/sk_stp.h"
#include "dumpfloppy/formats/shikadi/sk_super_street_fighter_ii_turbo_movie.h"
#include "dumpfloppy/formats/shikadi/sk_super_street_fighter_ii_turbo_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_fortune.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_info.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_map.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_message.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_monster.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_names.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_people.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_puzzle.h"
#include "dumpfloppy/formats/shikadi/sk_swords_of_glass_vault.h"
#include "dumpfloppy/formats/shikadi/sk_tbsa_music.h"
#include "dumpfloppy/formats/shikadi/sk_the_blues_brothers_huffman_compression.h"
#include "dumpfloppy/formats/shikadi/sk_the_blues_brothers_map.h"
#include "dumpfloppy/formats/shikadi/sk_the_blues_brothers_sprite.h"
#include "dumpfloppy/formats/shikadi/sk_the_incredible_machine_2_3_anm_file.h"
#include "dumpfloppy/formats/shikadi/sk_the_incredible_machine_image.h"
#include "dumpfloppy/formats/shikadi/sk_the_incredible_machine_level.h"
#include "dumpfloppy/formats/shikadi/sk_tim_resource.h"
#include "dumpfloppy/formats/shikadi/sk_titus_interactive_sqz_compression.h"
#include "dumpfloppy/formats/shikadi/sk_top_halloween_harry.h"
#include "dumpfloppy/formats/shikadi/sk_transylvania_font.h"
#include "dumpfloppy/formats/shikadi/sk_treasure_mountain_panning_image.h"
#include "dumpfloppy/formats/shikadi/sk_treasure_mountain_save_file.h"
#include "dumpfloppy/formats/shikadi/sk_trugg_level.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_full_screen_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_map.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_tile_graphic.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_i_town_map.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_ii_dungeon.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_ii_map.h"
#include "dumpfloppy/formats/shikadi/sk_ultima_ii_talk.h"
#include "dumpfloppy/formats/shikadi/sk_vga_palette.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_graphics.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_level.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_raw_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_save.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_screen.h"
#include "dumpfloppy/formats/shikadi/sk_vgfm_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_viacom_new_media_graphics_file.h"
#include "dumpfloppy/formats/shikadi/sk_visage.h"
#include "dumpfloppy/formats/shikadi/sk_visage_animation.h"
#include "dumpfloppy/formats/shikadi/sk_voc.h"
#include "dumpfloppy/formats/shikadi/sk_wacky_wheels_configuration.h"
#include "dumpfloppy/formats/shikadi/sk_wacky_wheels_high_score_files.h"
#include "dumpfloppy/formats/shikadi/sk_wacky_wheels_track.h"
#include "dumpfloppy/formats/shikadi/sk_wad.h"
#include "dumpfloppy/formats/shikadi/sk_wasteland_pic.h"
#include "dumpfloppy/formats/shikadi/sk_wav.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_aud.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_bitfont.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_cmp.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_cps.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_fading_table.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v1.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v2.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v3.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_font_v4.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_lcw.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_lzw_12.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_lzw_14.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_rle.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_rle_zero.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_dune_ii.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_lands_of_lore.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_td.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_shp_ts.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_unicode_bitfont.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_wsa.h"
#include "dumpfloppy/formats/shikadi/sk_westwood_xor_delta.h"
#include "dumpfloppy/formats/shikadi/sk_wing_commander_save_game.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_demo.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_highscore.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_level.h"
#include "dumpfloppy/formats/shikadi/sk_word_rescue_saved_game.h"
#include "dumpfloppy/formats/shikadi/sk_xmi.h"
#include "dumpfloppy/formats/shikadi/sk_zlib_compression.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_compression.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_high_scores.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_level.h"
#include "dumpfloppy/formats/shikadi/sk_zone_66_tileset.h"
#include "dumpfloppy/formats/shikadi/sk_zzt.h"

#include <vector>

namespace dumpfloppy
{

inline void append_generated_payload(std::vector<const file_format*>& out)
{
    static const formats::sk_3o_chasm_the_rift generated_payload_0{};
    out.push_back(&generated_payload_0);
    static const formats::sk_4md generated_payload_1{};
    out.push_back(&generated_payload_1);
    static const formats::sk_4x4_off_road_racing_full_screen_graphic generated_payload_2{};
    out.push_back(&generated_payload_2);
    static const formats::sk_4x4_off_road_racing_graphic generated_payload_3{};
    out.push_back(&generated_payload_3);
    static const formats::sk_4x4_off_road_racing_sprite generated_payload_4{};
    out.push_back(&generated_payload_4);
    static const formats::sk_adlib_instrument generated_payload_5{};
    out.push_back(&generated_payload_5);
    static const formats::sk_adlib_instrument_bank generated_payload_6{};
    out.push_back(&generated_payload_6);
    static const formats::sk_adlib_midi generated_payload_7{};
    out.push_back(&generated_payload_7);
    static const formats::sk_adlib_sound_effect generated_payload_8{};
    out.push_back(&generated_payload_8);
    static const formats::sk_adlib_timbre_bank generated_payload_9{};
    out.push_back(&generated_payload_9);
    static const formats::sk_agos_vga generated_payload_10{};
    out.push_back(&generated_payload_10);
    static const formats::sk_aiff generated_payload_11{};
    out.push_back(&generated_payload_11);
    static const formats::sk_all_dogs_archive generated_payload_12{};
    out.push_back(&generated_payload_12);
    static const formats::sk_all_dogs_rle_compression generated_payload_13{};
    out.push_back(&generated_payload_13);
    static const formats::sk_amf generated_payload_14{};
    out.push_back(&generated_payload_14);
    static const formats::sk_ani_chasm_the_rift generated_payload_15{};
    out.push_back(&generated_payload_15);
    static const formats::sk_apogee_sound_system_timbre generated_payload_16{};
    out.push_back(&generated_payload_16);
    static const formats::sk_art_build generated_payload_17{};
    out.push_back(&generated_payload_17);
    static const formats::sk_artcraft_resource_file generated_payload_18{};
    out.push_back(&generated_payload_18);
    static const formats::sk_audiot generated_payload_19{};
    out.push_back(&generated_payload_19);
    static const formats::sk_b800_text generated_payload_20{};
    out.push_back(&generated_payload_20);
    static const formats::sk_battle_isle_history_line_library generated_payload_21{};
    out.push_back(&generated_payload_21);
    static const formats::sk_battle_isle_history_line_map generated_payload_22{};
    out.push_back(&generated_payload_22);
    static const formats::sk_bgi_stroked_font generated_payload_23{};
    out.push_back(&generated_payload_23);
    static const formats::sk_bin_chasm_the_rift generated_payload_24{};
    out.push_back(&generated_payload_24);
    static const formats::sk_bin_fury_of_the_furries generated_payload_25{};
    out.push_back(&generated_payload_25);
    static const formats::sk_blk_fury_of_the_furries generated_payload_26{};
    out.push_back(&generated_payload_26);
    static const formats::sk_bmc generated_payload_27{};
    out.push_back(&generated_payload_27);
    static const formats::sk_bnk_halloween_harry generated_payload_28{};
    out.push_back(&generated_payload_28);
    static const formats::sk_bodyworks_voyager_savegame generated_payload_29{};
    out.push_back(&generated_payload_29);
    static const formats::sk_borland_graphics_interface generated_payload_30{};
    out.push_back(&generated_payload_30);
    static const formats::sk_captain_comic_ii_dialog generated_payload_31{};
    out.push_back(&generated_payload_31);
    static const formats::sk_captain_comic_ii_map generated_payload_32{};
    out.push_back(&generated_payload_32);
    static const formats::sk_captain_comic_ii_sprite generated_payload_33{};
    out.push_back(&generated_payload_33);
    static const formats::sk_captain_comic_ii_tileset generated_payload_34{};
    out.push_back(&generated_payload_34);
    static const formats::sk_captain_comic_image generated_payload_35{};
    out.push_back(&generated_payload_35);
    static const formats::sk_captain_comic_map generated_payload_36{};
    out.push_back(&generated_payload_36);
    static const formats::sk_captain_comic_sprite generated_payload_37{};
    out.push_back(&generated_payload_37);
    static const formats::sk_captain_comic_tileset generated_payload_38{};
    out.push_back(&generated_payload_38);
    static const formats::sk_car_carnivores generated_payload_39{};
    out.push_back(&generated_payload_39);
    static const formats::sk_car_chasm_the_rift generated_payload_40{};
    out.push_back(&generated_payload_40);
    static const formats::sk_carmack_compression generated_payload_41{};
    out.push_back(&generated_payload_41);
    static const formats::sk_castle_adventure_data generated_payload_42{};
    out.push_back(&generated_payload_42);
    static const formats::sk_castles_ii_siege_and_conquest_cluster generated_payload_43{};
    out.push_back(&generated_payload_43);
    static const formats::sk_castles_ii_siege_and_conquest_save_game generated_payload_44{};
    out.push_back(&generated_payload_44);
    static const formats::sk_cat_mps_labs generated_payload_45{};
    out.push_back(&generated_payload_45);
    static const formats::sk_catacomb_highscore generated_payload_46{};
    out.push_back(&generated_payload_46);
    static const formats::sk_catacomb_map generated_payload_47{};
    out.push_back(&generated_payload_47);
    static const formats::sk_catacomb_savegame generated_payload_48{};
    out.push_back(&generated_payload_48);
    static const formats::sk_catacomb_tileset generated_payload_49{};
    out.push_back(&generated_payload_49);
    static const formats::sk_cc generated_payload_50{};
    out.push_back(&generated_payload_50);
    static const formats::sk_cc1 generated_payload_51{};
    out.push_back(&generated_payload_51);
    static const formats::sk_cdfm generated_payload_52{};
    out.push_back(&generated_payload_52);
    static const formats::sk_cel_image generated_payload_53{};
    out.push_back(&generated_payload_53);
    static const formats::sk_centurion_font generated_payload_54{};
    out.push_back(&generated_payload_54);
    static const formats::sk_cfg_f1_manager_professional generated_payload_55{};
    out.push_back(&generated_payload_55);
    static const formats::sk_cfg_jill_of_the_jungle generated_payload_56{};
    out.push_back(&generated_payload_56);
    static const formats::sk_cga_palette generated_payload_57{};
    out.push_back(&generated_payload_57);
    static const formats::sk_chasm_inf generated_payload_58{};
    out.push_back(&generated_payload_58);
    static const formats::sk_chr_halloween_harry generated_payload_59{};
    out.push_back(&generated_payload_59);
    static const formats::sk_cmf generated_payload_60{};
    out.push_back(&generated_payload_60);
    static const formats::sk_cmp generated_payload_61{};
    out.push_back(&generated_payload_61);
    static const formats::sk_command_and_conquer_mission generated_payload_62{};
    out.push_back(&generated_payload_62);
    static const formats::sk_command_and_conquer_red_alert_tileset generated_payload_63{};
    out.push_back(&generated_payload_63);
    static const formats::sk_command_and_conquer_red_alert_vortex_lookup_table generated_payload_64{};
    out.push_back(&generated_payload_64);
    static const formats::sk_command_and_conquer_tileset generated_payload_65{};
    out.push_back(&generated_payload_65);
    static const formats::sk_commander_keen_1_3_level generated_payload_66{};
    out.push_back(&generated_payload_66);
    static const formats::sk_commander_keen_1_3_score generated_payload_67{};
    out.push_back(&generated_payload_67);
    static const formats::sk_commander_keen_ega_header generated_payload_68{};
    out.push_back(&generated_payload_68);
    static const formats::sk_con generated_payload_69{};
    out.push_back(&generated_payload_69);
    static const formats::sk_cosmo_level generated_payload_70{};
    out.push_back(&generated_payload_70);
    static const formats::sk_cosmo_tileinfo generated_payload_71{};
    out.push_back(&generated_payload_71);
    static const formats::sk_cosmo_tileset generated_payload_72{};
    out.push_back(&generated_payload_72);
    static const formats::sk_cover_girl_strip_poker_font generated_payload_73{};
    out.push_back(&generated_payload_73);
    static const formats::sk_cover_girl_strip_poker_text generated_payload_74{};
    out.push_back(&generated_payload_74);
    static const formats::sk_crunched_screen_image generated_payload_75{};
    out.push_back(&generated_payload_75);
    static const formats::sk_crystal_caves_map generated_payload_76{};
    out.push_back(&generated_payload_76);
    static const formats::sk_crystal_caves_sound generated_payload_77{};
    out.push_back(&generated_payload_77);
    static const formats::sk_cur generated_payload_78{};
    out.push_back(&generated_payload_78);
    static const formats::sk_dangerous_dave_level generated_payload_79{};
    out.push_back(&generated_payload_79);
    static const formats::sk_dangerous_dave_tileset generated_payload_80{};
    out.push_back(&generated_payload_80);
    static const formats::sk_dark_ages_map generated_payload_81{};
    out.push_back(&generated_payload_81);
    static const formats::sk_dat_bullfrog generated_payload_82{};
    out.push_back(&generated_payload_82);
    static const formats::sk_dat_california_games_ii generated_payload_83{};
    out.push_back(&generated_payload_83);
    static const formats::sk_dat_centurion_defender_of_rome generated_payload_84{};
    out.push_back(&generated_payload_84);
    static const formats::sk_dat_dr_riptide generated_payload_85{};
    out.push_back(&generated_payload_85);
    static const formats::sk_dat_fury_of_the_furries generated_payload_86{};
    out.push_back(&generated_payload_86);
    static const formats::sk_dat_god_of_thunder generated_payload_87{};
    out.push_back(&generated_payload_87);
    static const formats::sk_dat_highway_hunter generated_payload_88{};
    out.push_back(&generated_payload_88);
    static const formats::sk_dat_hocus_pocus generated_payload_89{};
    out.push_back(&generated_payload_89);
    static const formats::sk_dat_hugo generated_payload_90{};
    out.push_back(&generated_payload_90);
    static const formats::sk_dat_monster_bash generated_payload_91{};
    out.push_back(&generated_payload_91);
    static const formats::sk_dat_mystic_towers generated_payload_92{};
    out.push_back(&generated_payload_92);
    static const formats::sk_dat_papyrus generated_payload_93{};
    out.push_back(&generated_payload_93);
    static const formats::sk_dat_sango_fighter generated_payload_94{};
    out.push_back(&generated_payload_94);
    static const formats::sk_dat_the_lost_vikings generated_payload_95{};
    out.push_back(&generated_payload_95);
    static const formats::sk_dat_wacky_wheels generated_payload_96{};
    out.push_back(&generated_payload_96);
    static const formats::sk_dat_zool generated_payload_97{};
    out.push_back(&generated_payload_97);
    static const formats::sk_dave_2_huffman_compression generated_payload_98{};
    out.push_back(&generated_payload_98);
    static const formats::sk_dave_2_intro generated_payload_99{};
    out.push_back(&generated_payload_99);
    static const formats::sk_dave_2_tileset generated_payload_100{};
    out.push_back(&generated_payload_100);
    static const formats::sk_dave_score generated_payload_101{};
    out.push_back(&generated_payload_101);
    static const formats::sk_ddici_graphics generated_payload_102{};
    out.push_back(&generated_payload_102);
    static const formats::sk_death_rally_bpa generated_payload_103{};
    out.push_back(&generated_payload_103);
    static const formats::sk_death_rally_bpk generated_payload_104{};
    out.push_back(&generated_payload_104);
    static const formats::sk_death_rally_cmf generated_payload_105{};
    out.push_back(&generated_payload_105);
    static const formats::sk_death_rally_haf generated_payload_106{};
    out.push_back(&generated_payload_106);
    static const formats::sk_del generated_payload_107{};
    out.push_back(&generated_payload_107);
    static const formats::sk_demo_fury_of_the_furries generated_payload_108{};
    out.push_back(&generated_payload_108);
    static const formats::sk_dlt generated_payload_109{};
    out.push_back(&generated_payload_109);
    static const formats::sk_dma generated_payload_110{};
    out.push_back(&generated_payload_110);
    static const formats::sk_dmp generated_payload_111{};
    out.push_back(&generated_payload_111);
    static const formats::sk_doofus_game_data generated_payload_112{};
    out.push_back(&generated_payload_112);
    static const formats::sk_dro generated_payload_113{};
    out.push_back(&generated_payload_113);
    static const formats::sk_dsik_config generated_payload_114{};
    out.push_back(&generated_payload_114);
    static const formats::sk_dsik_module generated_payload_115{};
    out.push_back(&generated_payload_115);
    static const formats::sk_dta_fury_of_the_furries generated_payload_116{};
    out.push_back(&generated_payload_116);
    static const formats::sk_duke_1_demo generated_payload_117{};
    out.push_back(&generated_payload_117);
    static const formats::sk_duke_1_level generated_payload_118{};
    out.push_back(&generated_payload_118);
    static const formats::sk_duke_nukem_3d_palette generated_payload_119{};
    out.push_back(&generated_payload_119);
    static const formats::sk_duke_nukem_ii_actor_info generated_payload_120{};
    out.push_back(&generated_payload_120);
    static const formats::sk_duke_nukem_ii_animation generated_payload_121{};
    out.push_back(&generated_payload_121);
    static const formats::sk_duke_nukem_ii_czone generated_payload_122{};
    out.push_back(&generated_payload_122);
    static const formats::sk_duke_nukem_ii_demo generated_payload_123{};
    out.push_back(&generated_payload_123);
    static const formats::sk_duke_nukem_ii_full_screen_images generated_payload_124{};
    out.push_back(&generated_payload_124);
    static const formats::sk_duke_nukem_ii_map generated_payload_125{};
    out.push_back(&generated_payload_125);
    static const formats::sk_duke_nukem_ii_misc_files generated_payload_126{};
    out.push_back(&generated_payload_126);
    static const formats::sk_duke_nukem_ii_palette generated_payload_127{};
    out.push_back(&generated_payload_127);
    static const formats::sk_dune_2000_font generated_payload_128{};
    out.push_back(&generated_payload_128);
    static const formats::sk_dungeons_of_the_unforgiven_character_creation_text generated_payload_129{};
    out.push_back(&generated_payload_129);
    static const formats::sk_dungeons_of_the_unforgiven_player_character generated_payload_130{};
    out.push_back(&generated_payload_130);
    static const formats::sk_dynamix_font_v1 generated_payload_131{};
    out.push_back(&generated_payload_131);
    static const formats::sk_dynamix_font_v2_v3 generated_payload_132{};
    out.push_back(&generated_payload_132);
    static const formats::sk_dynamix_font_v4_v5 generated_payload_133{};
    out.push_back(&generated_payload_133);
    static const formats::sk_dynamix_font_v6 generated_payload_134{};
    out.push_back(&generated_payload_134);
    static const formats::sk_ega_palette generated_payload_135{};
    out.push_back(&generated_payload_135);
    static const formats::sk_egagraph generated_payload_136{};
    out.push_back(&generated_payload_136);
    static const formats::sk_epf generated_payload_137{};
    out.push_back(&generated_payload_137);
    static const formats::sk_esi generated_payload_138{};
    out.push_back(&generated_payload_138);
    static const formats::sk_exe generated_payload_139{};
    out.push_back(&generated_payload_139);
    static const formats::sk_executioners_archive generated_payload_140{};
    out.push_back(&generated_payload_140);
    static const formats::sk_executioners_font generated_payload_141{};
    out.push_back(&generated_payload_141);
    static const formats::sk_executioners_rle generated_payload_142{};
    out.push_back(&generated_payload_142);
    static const formats::sk_executioners_sprite generated_payload_143{};
    out.push_back(&generated_payload_143);
    static const formats::sk_eye_of_the_beholder_palette generated_payload_144{};
    out.push_back(&generated_payload_144);
    static const formats::sk_eye_of_the_beholder_save_game generated_payload_145{};
    out.push_back(&generated_payload_145);
    static const formats::sk_eye_of_the_beholder_vcn generated_payload_146{};
    out.push_back(&generated_payload_146);
    static const formats::sk_eye_of_the_beholder_vmp generated_payload_147{};
    out.push_back(&generated_payload_147);
    static const formats::sk_family_feud_question generated_payload_148{};
    out.push_back(&generated_payload_148);
    static const formats::sk_family_feud_question_flag generated_payload_149{};
    out.push_back(&generated_payload_149);
    static const formats::sk_family_feud_save_game generated_payload_150{};
    out.push_back(&generated_payload_150);
    static const formats::sk_flic generated_payload_151{};
    out.push_back(&generated_payload_151);
    static const formats::sk_gamedat_fury_of_the_furries generated_payload_152{};
    out.push_back(&generated_payload_152);
    static const formats::sk_gamemaps generated_payload_153{};
    out.push_back(&generated_payload_153);
    static const formats::sk_gem_font generated_payload_154{};
    out.push_back(&generated_payload_154);
    static const formats::sk_glb_galactix generated_payload_155{};
    out.push_back(&generated_payload_155);
    static const formats::sk_glb_raptor generated_payload_156{};
    out.push_back(&generated_payload_156);
    static const formats::sk_global_timbre_library generated_payload_157{};
    out.push_back(&generated_payload_157);
    static const formats::sk_gmf_halloween_harry generated_payload_158{};
    out.push_back(&generated_payload_158);
    static const formats::sk_god_of_thunder_level generated_payload_159{};
    out.push_back(&generated_payload_159);
    static const formats::sk_god_of_thunder_music generated_payload_160{};
    out.push_back(&generated_payload_160);
    static const formats::sk_god_of_thunder_tileset generated_payload_161{};
    out.push_back(&generated_payload_161);
    static const formats::sk_graphics_interchange generated_payload_162{};
    out.push_back(&generated_payload_162);
    static const formats::sk_grp generated_payload_163{};
    out.push_back(&generated_payload_163);
    static const formats::sk_gx2 generated_payload_164{};
    out.push_back(&generated_payload_164);
    static const formats::sk_gx_library generated_payload_165{};
    out.push_back(&generated_payload_165);
    static const formats::sk_halloween_harry_dialogue generated_payload_166{};
    out.push_back(&generated_payload_166);
    static const formats::sk_heretic_executable generated_payload_167{};
    out.push_back(&generated_payload_167);
    static const formats::sk_heroquest_exe_file generated_payload_168{};
    out.push_back(&generated_payload_168);
    static const formats::sk_heroquest_quest generated_payload_169{};
    out.push_back(&generated_payload_169);
    static const formats::sk_heroquest_savegame generated_payload_170{};
    out.push_back(&generated_payload_170);
    static const formats::sk_hi_octane_texture_atlas generated_payload_171{};
    out.push_back(&generated_payload_171);
    static const formats::sk_hi_zzt generated_payload_172{};
    out.push_back(&generated_payload_172);
    static const formats::sk_hocus_pocus_image generated_payload_173{};
    out.push_back(&generated_payload_173);
    static const formats::sk_hocus_pocus_map generated_payload_174{};
    out.push_back(&generated_payload_174);
    static const formats::sk_hocus_pocus_palette generated_payload_175{};
    out.push_back(&generated_payload_175);
    static const formats::sk_hocus_pocus_sfx generated_payload_176{};
    out.push_back(&generated_payload_176);
    static const formats::sk_hocus_pocus_sprite generated_payload_177{};
    out.push_back(&generated_payload_177);
    static const formats::sk_hocus_pocus_text generated_payload_178{};
    out.push_back(&generated_payload_178);
    static const formats::sk_hog generated_payload_179{};
    out.push_back(&generated_payload_179);
    static const formats::sk_homebrew_file_folder generated_payload_180{};
    out.push_back(&generated_payload_180);
    static const formats::sk_hs_major_stryker generated_payload_181{};
    out.push_back(&generated_payload_181);
    static const formats::sk_hsb_halloween_harry generated_payload_182{};
    out.push_back(&generated_payload_182);
    static const formats::sk_huffman_compression generated_payload_183{};
    out.push_back(&generated_payload_183);
    static const formats::sk_hugo_map generated_payload_184{};
    out.push_back(&generated_payload_184);
    static const formats::sk_human_machine_interfaces_midi generated_payload_185{};
    out.push_back(&generated_payload_185);
    static const formats::sk_ibk generated_payload_186{};
    out.push_back(&generated_payload_186);
    static const formats::sk_ico_halloween_harry generated_payload_187{};
    out.push_back(&generated_payload_187);
    static const formats::sk_id_software_rlew_compression generated_payload_188{};
    out.push_back(&generated_payload_188);
    static const formats::sk_imf generated_payload_189{};
    out.push_back(&generated_payload_189);
    static const formats::sk_img_meen generated_payload_190{};
    out.push_back(&generated_payload_190);
    static const formats::sk_imm_fury_of_the_furries generated_payload_191{};
    out.push_back(&generated_payload_191);
    static const formats::sk_ims generated_payload_192{};
    out.push_back(&generated_payload_192);
    static const formats::sk_indy_500_library generated_payload_193{};
    out.push_back(&generated_payload_193);
    static const formats::sk_ins_halloween_harry generated_payload_194{};
    out.push_back(&generated_payload_194);
    static const formats::sk_int_33_graphics_pointer_shape generated_payload_195{};
    out.push_back(&generated_payload_195);
    static const formats::sk_inverse_frequency_sound generated_payload_196{};
    out.push_back(&generated_payload_196);
    static const formats::sk_isle_of_the_dead_font generated_payload_197{};
    out.push_back(&generated_payload_197);
    static const formats::sk_jam generated_payload_198{};
    out.push_back(&generated_payload_198);
    static const formats::sk_jazz_2_music generated_payload_199{};
    out.push_back(&generated_payload_199);
    static const formats::sk_jazz_jackrabbit_bonus generated_payload_200{};
    out.push_back(&generated_payload_200);
    static const formats::sk_jazz_jackrabbit_bonusmap generated_payload_201{};
    out.push_back(&generated_payload_201);
    static const formats::sk_jazz_jackrabbit_cutscene generated_payload_202{};
    out.push_back(&generated_payload_202);
    static const formats::sk_jazz_jackrabbit_demo generated_payload_203{};
    out.push_back(&generated_payload_203);
    static const formats::sk_jazz_jackrabbit_font generated_payload_204{};
    out.push_back(&generated_payload_204);
    static const formats::sk_jazz_jackrabbit_map generated_payload_205{};
    out.push_back(&generated_payload_205);
    static const formats::sk_jazz_jackrabbit_menu generated_payload_206{};
    out.push_back(&generated_payload_206);
    static const formats::sk_jazz_jackrabbit_panel generated_payload_207{};
    out.push_back(&generated_payload_207);
    static const formats::sk_jazz_jackrabbit_planet generated_payload_208{};
    out.push_back(&generated_payload_208);
    static const formats::sk_jazz_jackrabbit_rle_compression generated_payload_209{};
    out.push_back(&generated_payload_209);
    static const formats::sk_jazz_jackrabbit_saved_game generated_payload_210{};
    out.push_back(&generated_payload_210);
    static const formats::sk_jazz_jackrabbit_score generated_payload_211{};
    out.push_back(&generated_payload_211);
    static const formats::sk_jazz_jackrabbit_sound generated_payload_212{};
    out.push_back(&generated_payload_212);
    static const formats::sk_jazz_jackrabbit_sprite generated_payload_213{};
    out.push_back(&generated_payload_213);
    static const formats::sk_jazz_jackrabbit_tile generated_payload_214{};
    out.push_back(&generated_payload_214);
    static const formats::sk_jill_of_the_jungle_map generated_payload_215{};
    out.push_back(&generated_payload_215);
    static const formats::sk_joesnd generated_payload_216{};
    out.push_back(&generated_payload_216);
    static const formats::sk_karl_morton_music generated_payload_217{};
    out.push_back(&generated_payload_217);
    static const formats::sk_keen_1_3_rle_compression generated_payload_218{};
    out.push_back(&generated_payload_218);
    static const formats::sk_keen_1_3_saved_game generated_payload_219{};
    out.push_back(&generated_payload_219);
    static const formats::sk_kings_bounty_graphics generated_payload_220{};
    out.push_back(&generated_payload_220);
    static const formats::sk_kings_bounty_map generated_payload_221{};
    out.push_back(&generated_payload_221);
    static const formats::sk_kings_bounty_music generated_payload_222{};
    out.push_back(&generated_payload_222);
    static const formats::sk_kings_bounty_saved_game generated_payload_223{};
    out.push_back(&generated_payload_223);
    static const formats::sk_kings_of_the_beach_font generated_payload_224{};
    out.push_back(&generated_payload_224);
    static const formats::sk_kings_of_the_beach_pak generated_payload_225{};
    out.push_back(&generated_payload_225);
    static const formats::sk_klm generated_payload_226{};
    out.push_back(&generated_payload_226);
    static const formats::sk_kmd_fury_of_the_furries generated_payload_227{};
    out.push_back(&generated_payload_227);
    static const formats::sk_knowledge_dynamics_lzw_compressor generated_payload_228{};
    out.push_back(&generated_payload_228);
    static const formats::sk_kort_bmp generated_payload_229{};
    out.push_back(&generated_payload_229);
    static const formats::sk_kort_font generated_payload_230{};
    out.push_back(&generated_payload_230);
    static const formats::sk_kort_image generated_payload_231{};
    out.push_back(&generated_payload_231);
    static const formats::sk_kort_sound_archive generated_payload_232{};
    out.push_back(&generated_payload_232);
    static const formats::sk_kris_music_system generated_payload_233{};
    out.push_back(&generated_payload_233);
    static const formats::sk_kris_music_system_voice generated_payload_234{};
    out.push_back(&generated_payload_234);
    static const formats::sk_kvx_build generated_payload_235{};
    out.push_back(&generated_payload_235);
    static const formats::sk_lang_txt_fury_of_the_furries generated_payload_236{};
    out.push_back(&generated_payload_236);
    static const formats::sk_lbm generated_payload_237{};
    out.push_back(&generated_payload_237);
    static const formats::sk_lbr generated_payload_238{};
    out.push_back(&generated_payload_238);
    static const formats::sk_lbx generated_payload_239{};
    out.push_back(&generated_payload_239);
    static const formats::sk_legend_of_seven_paladins_3d_archive generated_payload_240{};
    out.push_back(&generated_payload_240);
    static const formats::sk_lib_electronic_arts generated_payload_241{};
    out.push_back(&generated_payload_241);
    static const formats::sk_lib_mythos_software generated_payload_242{};
    out.push_back(&generated_payload_242);
    static const formats::sk_linear_executable_lx_le generated_payload_243{};
    out.push_back(&generated_payload_243);
    static const formats::sk_lion_king_level generated_payload_244{};
    out.push_back(&generated_payload_244);
    static const formats::sk_lmh_lmo_fury_of_the_furries generated_payload_245{};
    out.push_back(&generated_payload_245);
    static const formats::sk_lpcm generated_payload_246{};
    out.push_back(&generated_payload_246);
    static const formats::sk_lzss_compression generated_payload_247{};
    out.push_back(&generated_payload_247);
    static const formats::sk_lzw_compression generated_payload_248{};
    out.push_back(&generated_payload_248);
    static const formats::sk_m generated_payload_249{};
    out.push_back(&generated_payload_249);
    static const formats::sk_major_stryker_level generated_payload_250{};
    out.push_back(&generated_payload_250);
    static const formats::sk_major_stryker_save_game generated_payload_251{};
    out.push_back(&generated_payload_251);
    static const formats::sk_major_stryker_text generated_payload_252{};
    out.push_back(&generated_payload_252);
    static const formats::sk_major_stryker_tileset generated_payload_253{};
    out.push_back(&generated_payload_253);
    static const formats::sk_map_build generated_payload_254{};
    out.push_back(&generated_payload_254);
    static const formats::sk_map_shadowcaster generated_payload_255{};
    out.push_back(&generated_payload_255);
    static const formats::sk_mat generated_payload_256{};
    out.push_back(&generated_payload_256);
    static const formats::sk_mch generated_payload_257{};
    out.push_back(&generated_payload_257);
    static const formats::sk_mdi generated_payload_258{};
    out.push_back(&generated_payload_258);
    static const formats::sk_megatech_vol generated_payload_259{};
    out.push_back(&generated_payload_259);
    static const formats::sk_messages_fury_of_the_furries generated_payload_260{};
    out.push_back(&generated_payload_260);
    static const formats::sk_microsoft_basic_mml generated_payload_261{};
    out.push_back(&generated_payload_261);
    static const formats::sk_microsoft_bitmap_font generated_payload_262{};
    out.push_back(&generated_payload_262);
    static const formats::sk_microsoft_exepack generated_payload_263{};
    out.push_back(&generated_payload_263);
    static const formats::sk_microsoft_vector_font generated_payload_264{};
    out.push_back(&generated_payload_264);
    static const formats::sk_mid generated_payload_265{};
    out.push_back(&generated_payload_265);
    static const formats::sk_miscellaneous_wacky_wheels_file generated_payload_266{};
    out.push_back(&generated_payload_266);
    static const formats::sk_mix_westwood generated_payload_267{};
    out.push_back(&generated_payload_267);
    static const formats::sk_mod generated_payload_268{};
    out.push_back(&generated_payload_268);
    static const formats::sk_monster_bash_level generated_payload_269{};
    out.push_back(&generated_payload_269);
    static const formats::sk_monster_bash_saved_game generated_payload_270{};
    out.push_back(&generated_payload_270);
    static const formats::sk_monster_bash_sprite generated_payload_271{};
    out.push_back(&generated_payload_271);
    static const formats::sk_monster_bash_tileset generated_payload_272{};
    out.push_back(&generated_payload_272);
    static const formats::sk_moraff_help_file generated_payload_273{};
    out.push_back(&generated_payload_273);
    static const formats::sk_moraff_monster_map generated_payload_274{};
    out.push_back(&generated_payload_274);
    static const formats::sk_mus generated_payload_275{};
    out.push_back(&generated_payload_275);
    static const formats::sk_mystic_towers_pc_speaker_sound generated_payload_276{};
    out.push_back(&generated_payload_276);
    static const formats::sk_mystic_towers_sprite generated_payload_277{};
    out.push_back(&generated_payload_277);
    static const formats::sk_nnv generated_payload_278{};
    out.push_back(&generated_payload_278);
    static const formats::sk_nomad_3d_model generated_payload_279{};
    out.push_back(&generated_payload_279);
    static const formats::sk_nomad_sound generated_payload_280{};
    out.push_back(&generated_payload_280);
    static const formats::sk_nomad_text generated_payload_281{};
    out.push_back(&generated_payload_281);
    static const formats::sk_nova generated_payload_282{};
    out.push_back(&generated_payload_282);
    static const formats::sk_op2_bank generated_payload_283{};
    out.push_back(&generated_payload_283);
    static const formats::sk_oregon_trail_dialogue generated_payload_284{};
    out.push_back(&generated_payload_284);
    static const formats::sk_oregon_trail_high_scores generated_payload_285{};
    out.push_back(&generated_payload_285);
    static const formats::sk_oregon_trail_joystick_calibration generated_payload_286{};
    out.push_back(&generated_payload_286);
    static const formats::sk_oregon_trail_save_game generated_payload_287{};
    out.push_back(&generated_payload_287);
    static const formats::sk_oregon_trail_tombstones generated_payload_288{};
    out.push_back(&generated_payload_288);
    static const formats::sk_paganitzu_graphics generated_payload_289{};
    out.push_back(&generated_payload_289);
    static const formats::sk_paganitzu_level generated_payload_290{};
    out.push_back(&generated_payload_290);
    static const formats::sk_pak_the_learning_company generated_payload_291{};
    out.push_back(&generated_payload_291);
    static const formats::sk_pak_westwood generated_payload_292{};
    out.push_back(&generated_payload_292);
    static const formats::sk_papyrus_palette generated_payload_293{};
    out.push_back(&generated_payload_293);
    static const formats::sk_pcx generated_payload_294{};
    out.push_back(&generated_payload_294);
    static const formats::sk_pcx_library generated_payload_295{};
    out.push_back(&generated_payload_295);
    static const formats::sk_pharaohs_tomb_and_arctic_adventure_fullscreen_image generated_payload_296{};
    out.push_back(&generated_payload_296);
    static const formats::sk_pic generated_payload_297{};
    out.push_back(&generated_payload_297);
    static const formats::sk_pic_sexonix generated_payload_298{};
    out.push_back(&generated_payload_298);
    static const formats::sk_pod generated_payload_299{};
    out.push_back(&generated_payload_299);
    static const formats::sk_pr2 generated_payload_300{};
    out.push_back(&generated_payload_300);
    static const formats::sk_pref_dat_witchaven generated_payload_301{};
    out.push_back(&generated_payload_301);
    static const formats::sk_prehistorik_level generated_payload_302{};
    out.push_back(&generated_payload_302);
    static const formats::sk_prographx_toolbox_tileset generated_payload_303{};
    out.push_back(&generated_payload_303);
    static const formats::sk_prot_fury_of_the_furries generated_payload_304{};
    out.push_back(&generated_payload_304);
    static const formats::sk_protracker_studio_module generated_payload_305{};
    out.push_back(&generated_payload_305);
    static const formats::sk_raptor_animated_graphics generated_payload_306{};
    out.push_back(&generated_payload_306);
    static const formats::sk_raptor_pic generated_payload_307{};
    out.push_back(&generated_payload_307);
    static const formats::sk_raptor_tileset generated_payload_308{};
    out.push_back(&generated_payload_308);
    static const formats::sk_raw_adlib generated_payload_309{};
    out.push_back(&generated_payload_309);
    static const formats::sk_raw_cga_data generated_payload_310{};
    out.push_back(&generated_payload_310);
    static const formats::sk_raw_ega_data generated_payload_311{};
    out.push_back(&generated_payload_311);
    static const formats::sk_raw_vga_image generated_payload_312{};
    out.push_back(&generated_payload_312);
    static const formats::sk_realms_of_chaos_level generated_payload_313{};
    out.push_back(&generated_payload_313);
    static const formats::sk_realms_of_chaos_masked_tileset generated_payload_314{};
    out.push_back(&generated_payload_314);
    static const formats::sk_realms_of_chaos_sprite generated_payload_315{};
    out.push_back(&generated_payload_315);
    static const formats::sk_realms_of_chaos_tileset generated_payload_316{};
    out.push_back(&generated_payload_316);
    static const formats::sk_res_boppin generated_payload_317{};
    out.push_back(&generated_payload_317);
    static const formats::sk_res_stellar_7 generated_payload_318{};
    out.push_back(&generated_payload_318);
    static const formats::sk_rescue_rover_saved_game generated_payload_319{};
    out.push_back(&generated_payload_319);
    static const formats::sk_rff generated_payload_320{};
    out.push_back(&generated_payload_320);
    static const formats::sk_rle_compression generated_payload_321{};
    out.push_back(&generated_payload_321);
    static const formats::sk_rob_northern_compression generated_payload_322{};
    out.push_back(&generated_payload_322);
    static const formats::sk_rol generated_payload_323{};
    out.push_back(&generated_payload_323);
    static const formats::sk_rol_image_archive generated_payload_324{};
    out.push_back(&generated_payload_324);
    static const formats::sk_rsc_battlestar generated_payload_325{};
    out.push_back(&generated_payload_325);
    static const formats::sk_rsc_f1_manager_professional generated_payload_326{};
    out.push_back(&generated_payload_326);
    static const formats::sk_rtl generated_payload_327{};
    out.push_back(&generated_payload_327);
    static const formats::sk_rts generated_payload_328{};
    out.push_back(&generated_payload_328);
    static const formats::sk_s3m generated_payload_329{};
    out.push_back(&generated_payload_329);
    static const formats::sk_sango_fighter_rlc_compression generated_payload_330{};
    out.push_back(&generated_payload_330);
    static const formats::sk_sav_hocus_pocus generated_payload_331{};
    out.push_back(&generated_payload_331);
    static const formats::sk_sbi generated_payload_332{};
    out.push_back(&generated_payload_332);
    static const formats::sk_secret_agent_level generated_payload_333{};
    out.push_back(&generated_payload_333);
    static const formats::sk_selectware_archive generated_payload_334{};
    out.push_back(&generated_payload_334);
    static const formats::sk_setup_dat_witchaven generated_payload_335{};
    out.push_back(&generated_payload_335);
    static const formats::sk_sha generated_payload_336{};
    out.push_back(&generated_payload_336);
    static const formats::sk_shadow_warrior_1993_beta_background_image generated_payload_337{};
    out.push_back(&generated_payload_337);
    static const formats::sk_shadow_warrior_1993_beta_image generated_payload_338{};
    out.push_back(&generated_payload_338);
    static const formats::sk_shaws_nightmare_archive generated_payload_339{};
    out.push_back(&generated_payload_339);
    static const formats::sk_skyroads_compression generated_payload_340{};
    out.push_back(&generated_payload_340);
    static const formats::sk_skyroads_image generated_payload_341{};
    out.push_back(&generated_payload_341);
    static const formats::sk_skyroads_level generated_payload_342{};
    out.push_back(&generated_payload_342);
    static const formats::sk_skyroads_save_game generated_payload_343{};
    out.push_back(&generated_payload_343);
    static const formats::sk_slb generated_payload_344{};
    out.push_back(&generated_payload_344);
    static const formats::sk_smacker_video generated_payload_345{};
    out.push_back(&generated_payload_345);
    static const formats::sk_softdisk_library generated_payload_346{};
    out.push_back(&generated_payload_346);
    static const formats::sk_softmax_resource_file generated_payload_347{};
    out.push_back(&generated_payload_347);
    static const formats::sk_solar_winds_sprites generated_payload_348{};
    out.push_back(&generated_payload_348);
    static const formats::sk_sop generated_payload_349{};
    out.push_back(&generated_payload_349);
    static const formats::sk_space_crusade_savegame generated_payload_350{};
    out.push_back(&generated_payload_350);
    static const formats::sk_space_quest_v_font generated_payload_351{};
    out.push_back(&generated_payload_351);
    static const formats::sk_ssp generated_payload_352{};
    out.push_back(&generated_payload_352);
    static const formats::sk_stargunner_sprites generated_payload_353{};
    out.push_back(&generated_payload_353);
    static const formats::sk_stp generated_payload_354{};
    out.push_back(&generated_payload_354);
    static const formats::sk_super_street_fighter_ii_turbo_movie generated_payload_355{};
    out.push_back(&generated_payload_355);
    static const formats::sk_super_street_fighter_ii_turbo_sprite generated_payload_356{};
    out.push_back(&generated_payload_356);
    static const formats::sk_swords_of_glass_fortune generated_payload_357{};
    out.push_back(&generated_payload_357);
    static const formats::sk_swords_of_glass_graphic generated_payload_358{};
    out.push_back(&generated_payload_358);
    static const formats::sk_swords_of_glass_info generated_payload_359{};
    out.push_back(&generated_payload_359);
    static const formats::sk_swords_of_glass_map generated_payload_360{};
    out.push_back(&generated_payload_360);
    static const formats::sk_swords_of_glass_message generated_payload_361{};
    out.push_back(&generated_payload_361);
    static const formats::sk_swords_of_glass_monster generated_payload_362{};
    out.push_back(&generated_payload_362);
    static const formats::sk_swords_of_glass_names generated_payload_363{};
    out.push_back(&generated_payload_363);
    static const formats::sk_swords_of_glass_people generated_payload_364{};
    out.push_back(&generated_payload_364);
    static const formats::sk_swords_of_glass_puzzle generated_payload_365{};
    out.push_back(&generated_payload_365);
    static const formats::sk_swords_of_glass_vault generated_payload_366{};
    out.push_back(&generated_payload_366);
    static const formats::sk_tbsa_music generated_payload_367{};
    out.push_back(&generated_payload_367);
    static const formats::sk_the_blues_brothers_huffman_compression generated_payload_368{};
    out.push_back(&generated_payload_368);
    static const formats::sk_the_blues_brothers_map generated_payload_369{};
    out.push_back(&generated_payload_369);
    static const formats::sk_the_blues_brothers_sprite generated_payload_370{};
    out.push_back(&generated_payload_370);
    static const formats::sk_the_incredible_machine_2_3_anm_file generated_payload_371{};
    out.push_back(&generated_payload_371);
    static const formats::sk_the_incredible_machine_image generated_payload_372{};
    out.push_back(&generated_payload_372);
    static const formats::sk_the_incredible_machine_level generated_payload_373{};
    out.push_back(&generated_payload_373);
    static const formats::sk_tim_resource generated_payload_374{};
    out.push_back(&generated_payload_374);
    static const formats::sk_titus_interactive_sqz_compression generated_payload_375{};
    out.push_back(&generated_payload_375);
    static const formats::sk_top_halloween_harry generated_payload_376{};
    out.push_back(&generated_payload_376);
    static const formats::sk_transylvania_font generated_payload_377{};
    out.push_back(&generated_payload_377);
    static const formats::sk_treasure_mountain_panning_image generated_payload_378{};
    out.push_back(&generated_payload_378);
    static const formats::sk_treasure_mountain_save_file generated_payload_379{};
    out.push_back(&generated_payload_379);
    static const formats::sk_trugg_level generated_payload_380{};
    out.push_back(&generated_payload_380);
    static const formats::sk_ultima_i_full_screen_graphic generated_payload_381{};
    out.push_back(&generated_payload_381);
    static const formats::sk_ultima_i_map generated_payload_382{};
    out.push_back(&generated_payload_382);
    static const formats::sk_ultima_i_save_game generated_payload_383{};
    out.push_back(&generated_payload_383);
    static const formats::sk_ultima_i_tile_graphic generated_payload_384{};
    out.push_back(&generated_payload_384);
    static const formats::sk_ultima_i_town_map generated_payload_385{};
    out.push_back(&generated_payload_385);
    static const formats::sk_ultima_ii_dungeon generated_payload_386{};
    out.push_back(&generated_payload_386);
    static const formats::sk_ultima_ii_map generated_payload_387{};
    out.push_back(&generated_payload_387);
    static const formats::sk_ultima_ii_talk generated_payload_388{};
    out.push_back(&generated_payload_388);
    static const formats::sk_vga_palette generated_payload_389{};
    out.push_back(&generated_payload_389);
    static const formats::sk_vgfm_graphics generated_payload_390{};
    out.push_back(&generated_payload_390);
    static const formats::sk_vgfm_level generated_payload_391{};
    out.push_back(&generated_payload_391);
    static const formats::sk_vgfm_raw_tileset generated_payload_392{};
    out.push_back(&generated_payload_392);
    static const formats::sk_vgfm_save generated_payload_393{};
    out.push_back(&generated_payload_393);
    static const formats::sk_vgfm_screen generated_payload_394{};
    out.push_back(&generated_payload_394);
    static const formats::sk_vgfm_tileset generated_payload_395{};
    out.push_back(&generated_payload_395);
    static const formats::sk_viacom_new_media_graphics_file generated_payload_396{};
    out.push_back(&generated_payload_396);
    static const formats::sk_visage generated_payload_397{};
    out.push_back(&generated_payload_397);
    static const formats::sk_visage_animation generated_payload_398{};
    out.push_back(&generated_payload_398);
    static const formats::sk_voc generated_payload_399{};
    out.push_back(&generated_payload_399);
    static const formats::sk_wacky_wheels_configuration generated_payload_400{};
    out.push_back(&generated_payload_400);
    static const formats::sk_wacky_wheels_high_score_files generated_payload_401{};
    out.push_back(&generated_payload_401);
    static const formats::sk_wacky_wheels_track generated_payload_402{};
    out.push_back(&generated_payload_402);
    static const formats::sk_wad generated_payload_403{};
    out.push_back(&generated_payload_403);
    static const formats::sk_wasteland_pic generated_payload_404{};
    out.push_back(&generated_payload_404);
    static const formats::sk_wav generated_payload_405{};
    out.push_back(&generated_payload_405);
    static const formats::sk_westwood_aud generated_payload_406{};
    out.push_back(&generated_payload_406);
    static const formats::sk_westwood_bitfont generated_payload_407{};
    out.push_back(&generated_payload_407);
    static const formats::sk_westwood_cmp generated_payload_408{};
    out.push_back(&generated_payload_408);
    static const formats::sk_westwood_cps generated_payload_409{};
    out.push_back(&generated_payload_409);
    static const formats::sk_westwood_fading_table generated_payload_410{};
    out.push_back(&generated_payload_410);
    static const formats::sk_westwood_font_v1 generated_payload_411{};
    out.push_back(&generated_payload_411);
    static const formats::sk_westwood_font_v2 generated_payload_412{};
    out.push_back(&generated_payload_412);
    static const formats::sk_westwood_font_v3 generated_payload_413{};
    out.push_back(&generated_payload_413);
    static const formats::sk_westwood_font_v4 generated_payload_414{};
    out.push_back(&generated_payload_414);
    static const formats::sk_westwood_lcw generated_payload_415{};
    out.push_back(&generated_payload_415);
    static const formats::sk_westwood_lzw_12 generated_payload_416{};
    out.push_back(&generated_payload_416);
    static const formats::sk_westwood_lzw_14 generated_payload_417{};
    out.push_back(&generated_payload_417);
    static const formats::sk_westwood_rle generated_payload_418{};
    out.push_back(&generated_payload_418);
    static const formats::sk_westwood_rle_zero generated_payload_419{};
    out.push_back(&generated_payload_419);
    static const formats::sk_westwood_shp_dune_ii generated_payload_420{};
    out.push_back(&generated_payload_420);
    static const formats::sk_westwood_shp_lands_of_lore generated_payload_421{};
    out.push_back(&generated_payload_421);
    static const formats::sk_westwood_shp_td generated_payload_422{};
    out.push_back(&generated_payload_422);
    static const formats::sk_westwood_shp_ts generated_payload_423{};
    out.push_back(&generated_payload_423);
    static const formats::sk_westwood_unicode_bitfont generated_payload_424{};
    out.push_back(&generated_payload_424);
    static const formats::sk_westwood_wsa generated_payload_425{};
    out.push_back(&generated_payload_425);
    static const formats::sk_westwood_xor_delta generated_payload_426{};
    out.push_back(&generated_payload_426);
    static const formats::sk_wing_commander_save_game generated_payload_427{};
    out.push_back(&generated_payload_427);
    static const formats::sk_word_rescue_demo generated_payload_428{};
    out.push_back(&generated_payload_428);
    static const formats::sk_word_rescue_highscore generated_payload_429{};
    out.push_back(&generated_payload_429);
    static const formats::sk_word_rescue_level generated_payload_430{};
    out.push_back(&generated_payload_430);
    static const formats::sk_word_rescue_saved_game generated_payload_431{};
    out.push_back(&generated_payload_431);
    static const formats::sk_xmi generated_payload_432{};
    out.push_back(&generated_payload_432);
    static const formats::sk_zlib_compression generated_payload_433{};
    out.push_back(&generated_payload_433);
    static const formats::sk_zone_66_compression generated_payload_434{};
    out.push_back(&generated_payload_434);
    static const formats::sk_zone_66_high_scores generated_payload_435{};
    out.push_back(&generated_payload_435);
    static const formats::sk_zone_66_level generated_payload_436{};
    out.push_back(&generated_payload_436);
    static const formats::sk_zone_66_tileset generated_payload_437{};
    out.push_back(&generated_payload_437);
    static const formats::sk_zzt generated_payload_438{};
    out.push_back(&generated_payload_438);
}

} /* namespace dumpfloppy */

#endif /* DUMPFLOPPY_FORMATS_GENERATED_PAYLOAD_H */
