#!/usr/bin/env python3
"""Scan format headers and emit generated_{payload,container,filesystem}.h."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FMT_ROOT = ROOT / "include" / "dumpfloppy" / "formats"

CORE_SKIP = {
    "generated_formats.h",
    "generated_payload.h",
    "generated_container.h",
    "generated_filesystem.h",
    "fat12.h",
    "pkd.h",
    "com.h",
    "hxc_mfm.h",
    "box86f.h",
    "arc.h",
    "pop_arc.h",
}

CLASS_RE = re.compile(
    r"class\s+(\w+)\s+final\s*:\s*public\s+file_format",
    re.MULTILINE,
)
KIND_RE = re.compile(r"return\s+format_kind::(disk_image|file)")

# Archiveteam filesystem articles (not image containers).
FILESYSTEM_CLASSES = {
    "at_adfs",
    "at_apple_dos",
    "at_atari_fms",
    "at_cbm_1581_fs",
    "at_cbmfs",
    "at_cpm",
    "at_fat",
    "at_fat8",
    "at_ffs",
    "at_hfs",
    "at_ofs",
    "at_prodos",
    "at_trdos_fs",
}


def classify(name: str, text: str) -> str:
    match = KIND_RE.search(text)
    kind = match.group(1) if match else "file"
    if kind == "file":
        return "payload"
    if name in FILESYSTEM_CLASSES:
        return "filesystem"
    return "container"


def emit(bucket: str, classes: list[tuple[str, Path]]) -> Path:
    out_path = FMT_ROOT / f"generated_{bucket}.h"
    guard = f"DUMPFLOPPY_FORMATS_GENERATED_{bucket.upper()}_H"
    fn = f"append_generated_{bucket}"
    lines = [
        "/**",
        f" * @file generated_{bucket}.h",
        f" * @brief Auto-generated {bucket} format classes.",
        " * @warning Generated by scripts/gen_format_registry.py — do not edit.",
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        '#include "dumpfloppy/format.h"',
        "",
    ]
    for _name, path in classes:
        rel = path.relative_to(ROOT / "include")
        lines.append(f'#include "{rel.as_posix()}"')
    lines += [
        "",
        "#include <vector>",
        "",
        "namespace dumpfloppy",
        "{",
        "",
        f"inline void {fn}(std::vector<const file_format*>& out)",
        "{",
    ]
    for i, (name, _path) in enumerate(classes):
        lines.append(f"    static const formats::{name} generated_{bucket}_{i}{{}};")
        lines.append(f"    out.push_back(&generated_{bucket}_{i});")
    lines += [
        "}",
        "",
        "} /* namespace dumpfloppy */",
        "",
        f"#endif /* {guard} */",
        "",
    ]
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def main() -> None:
    headers = sorted(
        p for p in FMT_ROOT.rglob("*.h") if p.name not in CORE_SKIP
    )
    buckets: dict[str, list[tuple[str, Path]]] = {
        "payload": [],
        "container": [],
        "filesystem": [],
    }
    seen: set[str] = set()
    for path in headers:
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in CLASS_RE.finditer(text):
            name = match.group(1)
            if name in seen:
                raise SystemExit(f"duplicate class {name} in {path}")
            seen.add(name)
            buckets[classify(name, text)].append((name, path))

    for bucket, classes in buckets.items():
        out = emit(bucket, classes)
        print(f"wrote {out} ({len(classes)} formats)")

    stale = FMT_ROOT / "generated_formats.h"
    if stale.exists():
        stale.unlink()
        print(f"removed {stale}")


if __name__ == "__main__":
    main()
