#!/usr/bin/env python3
"""Scan format headers and emit include/dumpfloppy/formats/generated_formats.h."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FMT_ROOT = ROOT / "include" / "dumpfloppy" / "formats"
OUT = FMT_ROOT / "generated_formats.h"

CLASS_RE = re.compile(
    r"class\s+(\w+)\s+final\s*:\s*public\s+file_format",
    re.MULTILINE,
)


def main() -> None:
    headers = sorted(
        p
        for p in FMT_ROOT.rglob("*.h")
        if p.name not in {"generated_formats.h", "fat12.h", "pkd.h", "com.h",
                          "hxc_mfm.h", "box86f.h"}
    )
    classes: list[tuple[str, Path]] = []
    seen: set[str] = set()
    for path in headers:
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in CLASS_RE.finditer(text):
            name = match.group(1)
            if name in seen:
                raise SystemExit(f"duplicate class {name} in {path}")
            seen.add(name)
            classes.append((name, path))

    lines = [
        "/**",
        " * @file generated_formats.h",
        " * @brief Auto-generated includes + table of wiki format classes.",
        " * @warning Generated by scripts/gen_format_registry.py — do not edit.",
        " */",
        "#ifndef DUMPFLOPPY_FORMATS_GENERATED_FORMATS_H",
        "#define DUMPFLOPPY_FORMATS_GENERATED_FORMATS_H",
        "",
        "#include \"dumpfloppy/format.h\"",
        "",
    ]
    for _name, path in classes:
        rel = path.relative_to(ROOT / "include")
        lines.append(f'#include "{rel.as_posix()}"')
    lines += [
        "",
        "#include <vector>",
        "",
        "namespace dumpfloppy",
        "{",
        "",
        "inline void append_generated_formats(std::vector<const file_format*>& out)",
        "{",
    ]
    for i, (name, _path) in enumerate(classes):
        lines.append(f"    static const formats::{name} generated_{i}{{}};")
        lines.append(f"    out.push_back(&generated_{i});")
    lines += [
        "}",
        "",
        "} /* namespace dumpfloppy */",
        "",
        "#endif /* DUMPFLOPPY_FORMATS_GENERATED_FORMATS_H */",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(classes)} formats)")


if __name__ == "__main__":
    main()
